---
settings:
  name: Release notes
  rss_page: whats-new.html
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  release_notes_autogen:
    auto_release_notes_enabled: true
    repositories_features:
    - workload-fsx-ontap
    - workload-databases
    - workload-vmware
    - workload-genai
    - workload-setup-admin
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Versionshinweise zu BlueXP  Workload auf Werkseinstellungen
    url: "/index.html"
  - title: Neueste Änderungen
    url: "/whats-new.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
