---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: Informieren Sie sich über die neuesten Änderungen an den Workloads, die Teil der NetApp Workload Factory sind. 
---
= Aktuelle Änderungen in der NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Informieren Sie sich über die neuesten Änderungen an den Workloads, die Teil der NetApp Workload Factory sind.



== 04. Januar 2026



=== VMware-Workloads



==== Integration des KI-Assistenten auf der Startseite

Auf der Startseite der Workload Factory-Konsole ist der KI-Assistent „Ask me“ integriert, mit dem Sie Fragen zu Ihrer eigenen Speicherlandschaft stellen, personalisierte Einblicke direkt aus Ihrer Umgebung erhalten und auf frühere Konversationen zurückgreifen können. Sie können mit „Fragen Sie mich“ interagieren, um Ihre Workloads zu verstehen, Probleme zu beheben und mehr über Workload Factory zu erfahren – alles, ohne die Konsole zu verlassen.



== 18. Dezember 2025



=== Datenbank-Workloads



==== Verbesserungen der Active Directory-Integration

Workload Factory for Databases enthält drei neue Active Directory (AD)-Felder, die bei der Bereitstellung von Microsoft SQL Server mit der Option *Erweiterte Erstellung* verwendet werden. Diese Erweiterungen ermöglichen es Ihnen, Active Directory-Beitrittspräferenzen festzulegen und ein verwaltetes Dienstkonto zu verwenden.

Die neuen AD-Felder sind:

* Bevorzugter Domänencontroller
* Bevorzugter Pfad der Organisationseinheit
* Ziel-Active Directory-Gruppe


link:https://docs.netapp.com/us-en/workload-databases/create-database.html["Microsoft SQL Server bereitstellen"]



== 04. Dezember 2025



=== Amazon FSX für NetApp ONTAP



==== Unterstützung für AWS S3-Zugriffspunkte für FSx für ONTAP

NetApp Workload Factory unterstützt AWS S3-Zugriffspunkte für Ihre FSx for ONTAP Dateisysteme. Sie können Volumes mithilfe von S3-Zugriffspunkten erstellen, S3-Zugriffspunkte einem vorhandenen Volume zuweisen und S3-Zugriffspunkte über die Workload Factory-Konsole verwalten. Mithilfe eines S3-Zugriffspunkts können Sie über die AWS S3-APIs auf Dateidaten zugreifen, die sich auf SMB/CIFS- oder NFS-Volumes befinden. Dies ermöglicht Ihnen die Integration Ihrer vorhandenen Daten mit GenAI, ML und Analysen von AWS-Diensten, die S3-Zugriffspunkte unterstützen.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Erstellen Sie ein Volume mithilfe von S3-Zugriffspunkten"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["Verwalten von S3-Zugriffspunkten für ein Volume"]




== 27. November 2025



=== Amazon FSX für NetApp ONTAP



==== Blockgeräteunterstützung in NetApp Workload Factory

Verwalten Sie Ihre Blockgeräte effektiver mit der neu eingeführten Blockgeräteunterstützung in NetApp Workload Factory. Diese Funktion ermöglicht es Ihnen, Details anzuzeigen und die Kapazität von iSCSI-LUNs zu erhöhen, wodurch Sie mehr Flexibilität für Ihre Speicheranforderungen erhalten.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["Blockgeräte in Workload Factory verwalten"]



==== Gut strukturierte Analyse-Updates

Workload Factory analysiert Ihre FSx for ONTAP Dateisysteme für die folgenden Konfigurationen:

* Unnötige Snapshot-Löschung: Prüft, ob Volumes veraltete und unnötige Snapshots enthalten, die gelöscht werden können, um Kosten zu reduzieren.
* FlexGroup -Volumes-Rebalance: Prüft, ob die FlexGroup Volumes gleichmäßig auf die einzelnen Mitgliedsvolumes verteilt sind, um eine optimale Performance zu gewährleisten.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Sehen Sie sich den Status Ihrer FSx for ONTAP -Dateisysteme an"]



==== KI-Analysator für EMS-Ereignisse in NetApp Workload Factory

NetApp Workload Factory stellt einen KI-gestützten Analysator für ONTAP Event Management System (EMS)-Ereignisse vor. Diese Funktion hilft Ihnen, Probleme schnell zu erkennen und zu beheben, indem sie auf der Grundlage der Analyse von EMS-Ereignisdaten Erkenntnisse und Empfehlungen liefert.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/analyze-events.html["Analysieren Sie EMS-Ereignisse in Workload Factory."]



==== Überwachen Sie Kosten- und Nutzungstrends für FSx für ONTAP Dateisysteme

Sie können die Kosten- und Nutzungstrends Ihrer FSx for ONTAP -Dateisysteme direkt über die NetApp Workload Factory Konsole überwachen. Diese Funktion liefert Kennzahlen zum Speicherverbrauch und zu den Kosten sowie detaillierte Kostenaufstellungen und hilft Ihnen so, Ihre Ressourcenzuweisung und Budgetplanung zu optimieren.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-costs.html["Verfolgen Sie die Kosten für FSx für ONTAP Dateisysteme in Workload Factory"]



==== Verwalten von FSx-Tags für ein Dateisystem in NetApp Workload Factory

Verwalten Sie Ihre FSx-Tags für ein Dateisystem ganz einfach direkt über die NetApp Workload Factory Konsole. Diese Funktion ermöglicht das Hinzufügen, Bearbeiten oder Entfernen von Tags und ermöglicht so eine bessere Organisation und Kategorisierung Ihrer FSx for ONTAP -Dateisysteme.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-fsx-tags.html["Verwalten Sie FSx-Tags in Workload Factory"]



==== Cache-Kapazität für FSx für ONTAP Dateisysteme anpassen

Über die Workload Factory-Konsole können Sie die Kapazität für Cache-Volumes erhöhen und verringern.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["Cache-Volumes in Workload Factory verwalten"]



=== Datenbank-Workloads



==== Optimieren Sie die Einsparungen im Datenbankrechner für Amazon Elastic Block Store (EBS).

Zwei neue Funktionen des Rechners verbessern die Kostenersparnisanalyse beim Betrieb mehrerer Instanzen mit EBS-Speicher, sodass Sie durch den Wechsel zu FSx für ONTAP mehr sparen können.

* Workload Factory bietet eine konsolidierte Speicherlösung für mehrere Datenbank-Hosts auf einem FSx for ONTAP -Dateisystem. Durch diese Konsolidierung werden die Speicherkosten optimiert, indem die Anzahl der für mehrere Datenbankhosts benötigten Dateisysteme reduziert wird, was zu erheblichen Kosteneinsparungen führt.
* Workload Factory analysiert Ihre EBS-Leistungsnutzung und schlägt dann die beste und kosteneffizienteste FSx for ONTAP Konfiguration vor.


link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["Entdecken Sie die Einsparungen für erkannte EBS-Hosts"]



==== Ein Excel-Bericht ist für das übersichtliche Dashboard verfügbar.

Sie können einen Excel-Bericht des übersichtlichen Dashboards herunterladen. Der Bericht liefert den Status der gut strukturierten Datenbankressource und Empfehlungen für alle Ressourcenkonfigurationen, einschließlich Unterkonfigurationen für Betriebssystem und ONTAP.



==== Fehlerprotokollanalyse für Oracle-Datenbanken verfügbar

Der KI-gestützte Fehlerprotokollanalysator Agentic ist für Oracle-Datenbanken verfügbar. Die Funktion nutzt fortschrittliche Algorithmen des maschinellen Lernens, um Fehler in Protokolldateien automatisch zu erkennen und zu analysieren. Dieses Tool zielt darauf ab, den Fehlerbehebungsprozess zu optimieren, indem es Entwicklern auf der Grundlage der in den Protokollen erkannten Muster umsetzbare Erkenntnisse und Empfehlungen liefert.

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["Erfahren Sie mehr über den KI-gestützten Fehlerprotokollanalysator von Agentic"]



==== Gut konzipierte Analyse für Oracle

Die gut durchdachte Analyse beinhaltet zwei neue Speicherkonfigurationen. Die Analyse bewertet und behebt Konfigurationsprobleme im Zusammenhang mit der Zuweisung von Auslagerungsspeicher und dem Dateisystem-Spielraum für bestehende Oracle-Datenbankinstallationen.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementieren Sie gut strukturierte Datenbankkonfigurationen in Workload Factory"]



=== VMware-Workloads



==== Berechnen Sie die Kosteneinsparungen durch die Migration zu Amazon Elastic VMware Service für bestimmte Regionen

Sie können nun den Wert verschiedener Bereitstellungsoptionen für Ihre Cloud-Migration erkunden, den Aufwand für die Lösungsbewertung optimieren und sich eingehend mit Lösungen befassen, die das Potenzial haben, in der Cloud Mehrwert und Einsparungen zu bieten.

Sie können auch die Einsparungen an vCPU-Kernen überprüfen, die durch die Verwendung von FSx für ONTAP für eine EVS-Bereitstellung erzielt werden können.

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["Entdecken Sie die Einsparungen für Amazon Elastic VMware Service mit NetApp Workload Factory"]



=== Einrichtung und Administration



==== Berechtigungsaktualisierung für Speicher

Der FSx for ONTAP EMS-Ereignisanalysator verwendet die folgenden Amazon Bedrock-Berechtigungen in der Berechtigungsrichtlinie _operations and remediation_, um Ereignisdaten für die Storage-Workload abzurufen.

* `bedrock:ListInferenceProfiles`
* `bedrock:GetInferenceProfile`
* `bedrock:InvokeModelWithResponseStream`
* `bedrock:InvokeModel`


link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Änderungsprotokoll der Berechtigungsreferenz"]



== 02. November 2025



=== Amazon FSX für NetApp ONTAP



==== Cache-Volume-Verwaltung

Die folgenden Vorgänge zur Verwaltung des Cache-Volumes können Sie in der Workload Factory-Konsole durchführen:

* Cache-Namen bearbeiten
* Erhöhen Sie die Kapazität eines Cache-Volumes
* Bearbeiten Sie den Mount-Pfad oder die Exportrichtlinie für ein Cache-Volume.
* Ändern Sie die Caching-Methode oder den Modus für ein Cache-Volume.
* Cache-Volume vorbefüllen
* Löschen eines Cache-Volumes


link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["Cache-Volumes verwalten"]



==== Automatisches Inode-Management verfügbar

Die automatische Inode-Verwaltung kann aktiviert werden, ohne dass die automatische Kapazitätsverwaltung aktiviert werden muss.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["Automatische Inode-Verwaltung aktivieren"]



==== Schwellenwertwarnung für Kapazitäts- und Inode-Nutzung

Schwellenwertwarnungen sind sowohl für die Kapazität als auch für die Inode-Auslastung verfügbar. Diese Schwellenwerte können Sie beim Aktivieren der automatischen Kapazitäts- oder Inode-Verwaltung festlegen. Um diese Einstellung zu verwenden, müssen Sie Benachrichtigungen mithilfe der folgenden Funktion konfigurieren:link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["NetApp Workload Factory Benachrichtigungsdienst"^] Die



==== Volumenverkleinerung möglich

Sie können die Größe von NFS- und SMB/CIFS-Volumes in NetApp Workload Factory verringern. Diese Funktion ermöglicht eine bessere Verwaltung der Speicherressourcen, indem sie es Ihnen erlaubt, die Größe von Volumes zu reduzieren, die in ihrer aktuellen Kapazität nicht mehr benötigt werden.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/adjust-volume-capacity.html["Verringern Sie die Kapazität eines Volumens"]



==== Erweiterter FSx für ONTAP Ressourcenstatus

Workload Factory hat den Ressourcenstatus „falsch konfiguriert“ um eine Erläuterung des eigentlichen Problems für die Ressource erweitert.



==== Gut strukturierte Analyse-Updates

Workload Factory analysiert Ihre FSx for ONTAP Dateisysteme für die folgenden Konfigurationen:

* Die Speicherauslastung nähert sich der maximalen Kapazität: Es wird geprüft, ob Speichermedien 80 % oder mehr ihrer Dateikapazität nutzen. Dies hilft Ihnen, Volumina zu identifizieren, die möglicherweise zusätzliche Kapazität benötigen.
* Unberechtigter Zugriff auf Volumes: Prüft, ob ein iSCSI-Volume über einen NFS- oder SMB/CIFS-Mountpfad erreichbar ist, und ermöglicht es Ihnen, unberechtigten Zugriff auf das Volume zu entfernen, um Sicherheitsrisiken zu vermeiden.




==== Berechtigungsänderungen für Workload Factory für Speicher

Workload Factory bietet mehr Klarheit darüber, welche Berechtigungen für bestimmte Aktionen erforderlich sind, und ermöglicht die detaillierte Auswahl nur der benötigten Berechtigungen. Wenn Sie Anmeldeinformationen hinzufügen, stehen Ihnen drei Berechtigungsoptionen zur Auswahl, anstatt des bisherigen Berechtigungsmodells mit den Optionen „Nur lesen“ und „Lesen/Schreiben“. Das neue Berechtigungsmodell unterteilt die Berechtigungsrichtlinien wie folgt:

* _Ansicht, Planung und Analyse_: Sehen Sie sich FSx for ONTAP -Dateisysteme an, erfahren Sie mehr über den Systemzustand, erhalten Sie eine fundierte Analyse Ihrer Systeme und entdecken Sie Einsparmöglichkeiten.
* _Betrieb und Fehlerbehebung_: Führen Sie operative Aufgaben durch, wie z. B. die Anpassung der Dateisystemkapazität und die Behebung von Problemen in Ihren Dateisystemkonfigurationen.
* _Dateisystemerstellung und -löschung_: Erstellen und Löschen von FSx-Dateisystemen und Speicher-VMs für ONTAP .


Beim Hinzufügen von Anmeldeinformationen können Sie eine oder mehrere dieser Berechtigungsrichtlinien auswählen, je nachdem, welchen Zugriff Sie Workload Factory gewähren möchten.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Referenz zu den Berechtigungen der Workload Factory"]



==== FSx für ONTAP Cyber ​​Vault-Unterstützung

Sie können einen Cyber-Tresor erstellen, indem Sie FSx für ONTAP als Quelle oder Ziel in der Cyber-Tresor-Architektur verwenden. Cyber-Tresore bieten eine sichere und isolierte Umgebung zur Speicherung kritischer Daten und schützen diese vor Ransomware und anderen Cyberbedrohungen.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-cyber-vault.html["Richten Sie einen Cyber-Tresor mit FSx für ONTAP ein."]



=== Datenbank-Workloads



==== Verbesserungen am Dashboard

Das neue Dashboard ist übersichtlicher und besser organisiert, um einen klareren Überblick über Ihre Datenbankressourcen und die wichtigsten Funktionen von Workload Factory auf einem Bildschirm zu bieten; eine Karte hebt die Datenbankressourcen hervor, eine Karte liefert Informationen über den Well-Architected Score und die Analyse, eine Karte zeigt die Fehleranalyse an, zwei Karten zeigen die monatlichen Kosten und die potenziellen Einsparungen an und eine Karte zeigt Informationen zu Sandboxes an.



==== Gut konzipierte Analyse für Oracle

Die gut durchdachte Analyse umfasst die folgenden Bewertungen und Korrekturen für Oracle-Konfigurationen:

* Speicherkonfigurationsbetriebssystem unter Verwendung des NFS-Protokolls: Bewertet und behebt Konfigurationsprobleme mit der NFS-Konfiguration für bestehende Oracle-Datenbankbereitstellungen.
* Speicherkonfigurationsbetriebssystem unter Verwendung des iSCSI-Protokolls: Bewertet und behebt Konfigurationsprobleme mit der iSCSI-Konfiguration für bestehende Oracle-Datenbankbereitstellungen.
* Speicherkonfigurationsbetriebssystem unter Verwendung von Automatic Storage Management (ASM): bewertet Konfigurationsprobleme mit der ASM-Konfiguration für bestehende Oracle-Datenbankbereitstellungen.


link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementieren Sie gut strukturierte Datenbankkonfigurationen in Workload Factory"]



==== Berechtigungsänderungen für Workload Factory für Datenbanken

Workload Factory for Databases hat die Berechtigungsrichtlinien aktualisiert, um mehr Klarheit darüber zu schaffen, was für bestimmte Aktionen erforderlich ist, und um eine feinere Auswahlmöglichkeit für die benötigten Berechtigungen zu bieten. Wenn Sie Anmeldeinformationen hinzufügen, stehen Ihnen drei Berechtigungsoptionen zur Auswahl, anstatt des bisherigen Berechtigungsmodells mit den Optionen „Nur lesen“ und „Lesen/Schreiben“. Das neue Berechtigungsmodell unterteilt die Berechtigungsrichtlinien wie folgt:

* Ansicht, Planung und Analyse: Sehen Sie sich den Bestand Ihrer Datenbankressourcen an, informieren Sie sich über deren Zustand, prüfen Sie die detaillierte Analyse Ihrer Datenbankkonfigurationen, erhalten Sie eine Fehlerprotokollanalyse und entdecken Sie Einsparmöglichkeiten.
* Betrieb und Fehlerbehebung: Wir führen operative Aufgaben für Ihre Datenbankressourcen durch und beheben Probleme mit Datenbankkonfigurationen und dem zugrunde liegenden FSx for ONTAP Dateisystemspeicher.
* _Erstellung von Datenbankhosts_: Bereitstellung von Datenbankhosts und des zugrunde liegenden FSx for ONTAP Dateisystems gemäß bewährten Verfahren


Beim Hinzufügen von Anmeldeinformationen können Sie eine oder mehrere dieser Berechtigungsrichtlinien auswählen, je nachdem, welchen Zugriff Sie Workload Factory for Databases gewähren möchten.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Referenz zu den Berechtigungen der Workload Factory"^]



==== Gut gestalteter Dashboard-Bildschirm hinzugefügt

Dem Menü „Datenbanken“ wurde ein neues, übersichtliches Dashboard hinzugefügt. Auf diesem Bildschirm erhalten Sie eine Gesamtübersicht über den Konfigurationsstatus Ihrer gesamten Datenbanklandschaft.



==== Bearbeitungsschutz für Datenbankbereitstellungen in NetApp Backup and Recovery

In der Workload Factory-Konsole können Sie die Bearbeitung des Schutzes für eine geschützte Ressource auswählen. Anschließend werden Sie zur Sicherung und Wiederherstellung in der NetApp Console weitergeleitet, wo Sie die Schutzrichtlinie oder den Zeitplan ändern können.

link:https://docs.netapp.com/us-en/workload-databases/protect-sql-server.html["Bearbeitungsschutz für Datenbankbereitstellungen"]



==== Fehlerfilterung nach Tags, die für die Fehleranalysefunktion verfügbar sind

Sie können Microsoft SQL Server-Fehlerprotokolle anhand von infrastrukturorientierten Tags filtern und anzeigen, wenn Sie die Fehleranalysefunktion in Workload Factory verwenden. Diese Erweiterung hilft Ihnen, Probleme schnell zu priorisieren, zu analysieren und zu beheben.

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["Analysieren Sie Fehlerprotokolle mithilfe von Tag-Filtern."^]



=== VMware-Workloads



==== Einführung der Amazon Elastic VMware Service-Einstellungen im FSx for ONTAP Dateisystembereitstellungsassistenten

Wenn Sie ein FSx for ONTAP Dateisystem zur Verwendung als externer NFS-Datenspeicher für Amazon Elastic VMware Service bereitstellen, können Sie nun die EVS-Umgebung auswählen, in der die Datenspeicher verbunden werden sollen. Dadurch werden mehrere Felder im Bereitstellungsassistenten automatisch ausgefüllt, um den Bereitstellungsprozess zu vereinfachen.

https://docs.netapp.com/us-en/workload-vmware/deploy-fsx-file-system-evs.html["Stellen Sie das empfohlene FSx-Dateisystem für ONTAP bereit."]



==== Berechtigungsänderungen für VMware-Workloads

VMware Workloads bietet mehr Klarheit über die für bestimmte Aktionen erforderlichen Berechtigungen und eine höhere Granularität bei der Auswahl nur der benötigten Berechtigungen. Wenn Sie Anmeldeinformationen hinzufügen, stehen Ihnen zwei Berechtigungsoptionen zur Auswahl, anstatt des bisherigen Berechtigungsmodells, das aus _nur_lesen_ und _lesen/schreiben_ bestand. Das neue Berechtigungsmodell unterteilt die Berechtigungsrichtlinien wie folgt:

* _Ansicht, Planung und Analyse_: Sehen Sie sich den Bestand an EVS-Virtualisierungsumgebungen an, erhalten Sie eine fundierte Analyse Ihrer Systeme und entdecken Sie Einsparmöglichkeiten.
* _Bereitstellung und Konnektivität von Datenspeichern_: Stellen Sie empfohlene VM-Layouts auf Amazon EVS-, Amazon EC2- oder VMware Cloud on AWS vSphere-Clustern bereit und verwenden Sie angepasste Amazon FSx for NetApp ONTAP Dateisysteme als externe Datenspeicher.


Beim Hinzufügen von Anmeldeinformationen können Sie eine oder mehrere dieser Berechtigungsrichtlinien auswählen, je nachdem, welchen Zugriff Sie VMware-Workloads gewähren möchten.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Referenz zu den Berechtigungen der Workload Factory"^]



==== Verbesserungen am Amazon EC2 Migrationsberater

Diese Version von NetApp Workload Factory für VMware bietet mehrere Verbesserungen für die Benutzererfahrung des Migrationsberaters:

* *Migrationsplan speichern oder herunterladen*: Sie können jetzt einen Migrationsplan als PDF- oder CSV-Datei speichern oder herunterladen. Wenn Sie einen Migrationsplan speichern, wird dieser Plan in Ihrem Workload Factory-Konto gespeichert.




=== Einrichtung und Administration



==== Berechtigungsaktualisierung

In dieser Version haben wir bedeutende Aktualisierungen an den Berechtigungsrichtlinien für Speicher-, Datenbank- und VMware-Workloads vorgenommen, um die Sicherheit und die Benutzerkontrolle zu verbessern. Sie können Ihre Berechtigungseinstellungen detaillierter anpassen und Berechtigungen nach Bedarf hinzufügen oder entfernen.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Berechtigungsreferenz für Workload Factory"]



==== Neue Benachrichtigung für Speicher

Der NetApp Workload Factory Benachrichtigungsdienst umfasst die Benachrichtigung für die automatische Inode-Verwaltung für Speicher.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Benachrichtigungen für NetApp Workload Factory"]



==== Schwellenwertwarnungen für die automatische Kapazitäts- und Inode-Verwaltung

Die automatische Kapazitäts- und Inode-Verwaltung für den Speicher kann mit einem Warnschwellenwert eingerichtet werden, der eine Benachrichtigung vom Workload Factory-Benachrichtigungsdienst auslöst. Um diese Funktion nutzen zu können, müssen Sie zuerst den Workload Factory-Benachrichtigungsdienst aktivieren.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Konfigurieren Sie Benachrichtigungen für NetApp Workload Factory"]
