= 1 2024-08-04
:allow-uri-read: 




== 1 2024-08-04

Ungelöste Direktive in <stdin> - include:_include/Workload-fsx-ONTAP.adoc[] :leveloffset: +1



=== Terraform-Unterstützung

Mit Terraform aus der Codebox können Dateisysteme und Storage-VMs implementiert und gemanagt werden.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Erstellen Sie ein Dateisystem"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-storage-vm.html["Erstellen einer Storage-VM"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Verwenden Sie Terraform aus der Codebox"^]




=== Empfehlungen zu Durchsatz und IOPS im Storage-Rechner

Der Storage-Rechner gibt Empfehlungen für die Konfiguration des Filesystems FSX für ONTAP für Durchsatz und IOPS auf Basis von AWS Best Practices ab, damit Sie optimale Hinweise für Ihre Auswahl erhalten.



== 1 2024-07-07

Ungelöste Direktive in <stdin> - include:_include/Workload-fsx-ONTAP.adoc[] :leveloffset: +1



=== Erste Version von Workload Factory für Amazon FSX for NetApp ONTAP

Amazon FSX for NetApp ONTAP ist in Workload Factory allgemein verfügbar.
