---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: Informieren Sie sich über die neuesten Änderungen an den Workloads, die Teil der BlueXP -Workload-Fabrik sind. 
---
= Kürzliche Änderungen in der BlueXP  Workload-Farm
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Informieren Sie sich über die neuesten Änderungen an den Workloads, die Teil der BlueXP -Workload-Fabrik sind.



== 03.08.2025



=== Amazon FSX für NetApp ONTAP



==== Verbesserungen an der Registerkarte „Replikationsbeziehungen“

Wir haben der Tabelle mit den Replikationsbeziehungen mehrere neue Spalten hinzugefügt, um Ihnen auf der Registerkarte *Replikationsbeziehungen* weitere Informationen zu Ihren Replikationsbeziehungen zu geben. Die Tabelle enthält jetzt die folgenden Spalten:

* SnapMirror -Richtlinie
* Quelldateisystem
* Zieldateisystem
* Stand der Beziehung
* Letzte Übertragungszeit




==== Verbesserungen des autonomen Ransomware-Schutzes von NetApp mit KI (ARP/AI)

In dieser Version wird der aktualisierte Begriff „NetApp Autonomous Ransomware Protection with AI (ARP/AI)“ eingeführt, um die Integration künstlicher Intelligenz in unsere Ransomware-Schutzfunktionen besser widerzuspiegeln.

Darüber hinaus wurden die folgenden Verbesserungen an ARP/AI vorgenommen:

* ARP/AI auf Volume-Ebene: Sie können jetzt ARP/AI auf Volume-Ebene aktivieren und so bestimmte Volumes innerhalb Ihrer FSx for ONTAP Dateisysteme schützen.
* Automatische Snapshot-Erstellung: Sie können die ARP/AI-Richtlinie so einstellen, dass automatische Snapshots erstellt werden, und festlegen, wie oft Snapshots für Volumes mit aktiviertem ARP/AI erstellt werden, wodurch Ihre Datenschutzstrategie verbessert wird.
* Unveränderliche Snapshots: ARP/AI unterstützt jetzt unveränderliche Snapshots, die nicht gelöscht oder geändert werden können und so eine zusätzliche Sicherheitsebene gegen Ransomware-Angriffe bieten.
* Erkennung: umfasst verschiedene Erkennungsmethoden wie beispielsweise eine hohe Entropie-Datenrate auf Datenträgerebene, Dateierstellungsrate, Dateiumbenennungsrate, Dateilöschrate und Verhaltensanalyse sowie nie zuvor gesehene Dateierweiterungen, die dabei helfen, Anomalien und potenzielle Ransomware-Angriffe zu erkennen.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Schützen Sie Ihre Daten mit NetApp Autonomous Ransomware Protection mit KI (ARP/AI)"]



==== Gut strukturierte Analyse-Updates

Workload Factory analysiert jetzt Ihre FSx for ONTAP Dateisysteme für die folgenden Konfigurationen:

* Zuverlässigkeit der Langzeitaufbewahrungsdaten: Überprüft, ob die der Snapshot-Richtlinie des Quellvolumes zugewiesenen Bezeichnungen mit den der Langzeitaufbewahrungsrichtlinie zugewiesenen Bezeichnungen identisch sind. Wenn die Bezeichnungen identisch sind, ist die Datenreplikation zwischen Quell- und Zielvolumes zuverlässig.
* NetApp Autonomous Ransomware Protection mit KI (ARP/AI): Überprüft, ob ARP/AI auf Ihren Dateisystemen aktiviert ist. Diese Funktion hilft Ihnen, Ransomware-Angriffe zu erkennen und sich davon zu erholen.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Sehen Sie sich den Status Ihrer FSx for ONTAP -Dateisysteme an"]



==== Eine Konfiguration aus der Well-Architected-Analyse verwerfen

Sie können jetzt eine oder mehrere Konfigurationen aus der Well-Architected-Analyse ausschließen. Auf diese Weise können Sie bestimmte Konfigurationen ignorieren, die Sie im Moment nicht ansprechen möchten.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Eine Konfiguration aus der Well-Architected-Analyse verwerfen"]



==== Terraform-Unterstützung für die Linkerstellung

Sie können jetzt Terraform aus der Codebox verwenden, um einen Link zur Zuordnung zu einem FSx für ONTAP Dateisystem zu erstellen. Diese Funktion ist für Benutzer gedacht, die Links manuell erstellen.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Stellen Sie über einen Lambda-Link eine Verbindung zu einem FSX für ONTAP-Dateisystem her"]



==== Neue regionale Unterstützung zur Ermittlung von Einsparungen bei der Speicherung

Die folgenden neuen Regionen werden jetzt unterstützt, um Einsparungen für Amazon Elastic Block Store (EBS), FSx für Windows File Server und Elastic File Systems (EFS) zu erkunden:

* Mexiko
* Thailand




==== Verbesserungen bei der Erstellung und Verwaltung von SMB/CIFS-Freigaben

Sie können jetzt SMB/CIFS-Freigaben erstellen, die auf Verzeichnisse innerhalb eines Volumes verweisen. Innerhalb des Volumes können Sie sehen, welche Freigaben vorhanden sind, wohin die Freigaben verweisen und welche Berechtigungen bestimmten Benutzern und Gruppen erteilt wurden.

Bei Datensicherungsvolumes umfasst der Ablauf zum Erstellen einer SMB/CIFS-Freigabe jetzt die Erstellung eines Verbindungspfads zum Volume für Bereitstellungszwecke.

link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_grogu-5684-wa-dismiss/manage-cifs-share.html#create-a-cifs-share-for-a-volume["Erstellen einer CIFS-Freigabe für ein Volume"]



=== VMware-Workloads



==== Verbesserte Migrationsberaterunterstützung für Amazon Elastic VMWare Service

Der Migrationsberater des Amazon Elastic VMware Service unterstützt jetzt die automatische Bereitstellung und Bereitstellung Ihres Amazon FSx for NetApp ONTAP Dateisystems. Auf diese Weise können Sie mit der Bereitstellung Ihrer VMs auf FSx für ONTAP -Dateisystemen beginnen, wenn die Migration zur Amazon EVS-Umgebung abgeschlossen ist.

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["Erstellen Sie einen Bereitstellungsplan für Amazon EVS mit dem Migrationsberater"]



==== Berechnen Sie die Kosteneinsparungen durch die Migration zum Amazon Elastic VMware Service

Sie können jetzt die potenziellen Einsparungen durch die Migration Ihrer VMware-Workloads zu Amazon Elastic VMware Service (EVS) erkunden. Mit dem Einsparungsrechner können Sie die Kosten für die Verwendung von Amazon EVS mit und ohne Amazon FSx for NetApp ONTAP als zugrunde liegenden Speicher vergleichen. Der Rechner zeigt potenzielle Einsparungen in Echtzeit an, während Sie die Eigenschaften Ihrer Umgebung anpassen.

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["Entdecken Sie die Einsparungen für Amazon Elastic VMware Service mit der BlueXP workload factory"]



== 1 2025-06-30



=== Datenbank-Workloads



==== Unterstützung des BlueXP Workload Factory-Benachrichtigungsdienstes

Der Benachrichtigungsdienst der BlueXP Workload Factory ermöglicht es der Workload Factory, Benachrichtigungen an den BlueXP-Warndienst oder an ein Amazon SNS-Thema zu senden. An BlueXP-Warnmeldungen gesendete Benachrichtigungen werden im BlueXP-Warnmeldungsbereich angezeigt. Wenn die Workload Factory Benachrichtigungen an ein Amazon SNS-Thema veröffentlicht, erhalten Abonnenten des Themas (z. B. Benutzer oder andere Anwendungen) die Benachrichtigungen an den für das Thema konfigurierten Endpunkten (z. B. per E-Mail oder SMS).

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Konfigurieren Sie die Benachrichtigungen der BlueXP-Workload-Factory"^]

Workload Factory bietet die folgenden Benachrichtigungen für Datenbanken:

* Gut strukturierter Bericht
* Hostbereitstellung




==== Onboarding-Erweiterung für die Registrierung von Instanzen

Workload Factory für Datenbanken hat den Onboarding-Prozess für die Registrierung von Instanzen auf Amazon FSx für NetApp ONTAP-Speicher verbessert. Sie können jetzt Instanzen gleichzeitig zur Registrierung auswählen. Sobald eine Instanz registriert ist, können Sie Datenbankressourcen in der Workload Factory-Konsole erstellen und verwalten.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["Instanzmanagement"]



==== Analyse und Fehlerbehebung für die Microsoft Multipath I/O-Timeout-Einstellung

Der Well-Architected-Status für Ihre Datenbankinstanzen umfasst jetzt die Analyse und den Fix für die Timeout-Einstellung von Microsoft Multipath I/O (MPIO). Einstellung des MPIO-Timeouts auf 60 Sekunden gewährleistet die FSx für ONTAP-Speicherkonnektivität und Stabilität bei Failovers. Sollte die MPIO-Einstellung nicht entsprechend eingestellt sein, stellt Workload Factory einen Fix bereit, um den MPIO-Timeout-Wert auf 60 Sekunden festzulegen.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementieren Sie gut strukturierte Datenbankkonfigurationen in der Workload Factory"]



==== Verbesserungen der Grafiken im Instanzinventar

Auf dem Bildschirm „Instanzinventar“ werden jetzt in verschiedenen Diagrammen zur Ressourcenauslastung, beispielsweise zu Durchsatz und IOPS, Daten der letzten 7 Tage angezeigt, sodass Sie die Leistung von SQL-Knoten von der Workload Factory-Konsole aus effizienter überwachen können. Die von den SQL-Knoten erfassten Leistungsmetriken werden in Amazon CloudWatch gespeichert und können für Logs Insights oder die Integration mit anderen Analysediensten in Ihrer Umgebung verwendet werden.

Auf den Registerkarten „Instanzen“ und „Datenbanken“ im Inventar haben wir die Beschreibung und Visualisierung zum Schutz verbessert.



==== Unterstützung für Windows-Authentifizierung in der Workload Factory

Jetzt unterstützt Workload Factory die SQL Server-Authentifizierung mithilfe von Windows-authentifizierten Benutzern, um Instanzen zu registrieren und von Verwaltungsfunktionen zu profitieren.

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html["Registrieren Sie Instanzen in der Workload Factory für Datenbanken"]



== 1 2025-06-29



=== Amazon FSX für NetApp ONTAP



==== Unterstützung des BlueXP Workload Factory-Benachrichtigungsdienstes

Der Benachrichtigungsdienst der BlueXP Workload Factory ermöglicht es der Workload Factory, Benachrichtigungen an den BlueXP-Warndienst oder an ein Amazon SNS-Thema zu senden. An BlueXP-Warnmeldungen gesendete Benachrichtigungen werden im BlueXP-Warnmeldungsbereich angezeigt. Wenn die Workload Factory Benachrichtigungen an ein Amazon SNS-Thema veröffentlicht, erhalten Abonnenten des Themas (z. B. Benutzer oder andere Anwendungen) die Benachrichtigungen an den für das Thema konfigurierten Endpunkten (z. B. per E-Mail oder SMS).

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Konfigurieren Sie die Benachrichtigungen der BlueXP-Workload-Factory"^]



==== Verbesserungen des Speicher-Dashboards

Das Speicher-Dashboard in der Workload Factory-Konsole enthält neue Karten für Einsparmöglichkeiten. Die Karte oben im Dashboard zeigt die Anzahl der Einsparmöglichkeiten für Speicherumgebungen an, die auf Amazon Elastic Block Store (EBS), Amazon FSx für Windows File Server und Amazon Elastic File Systems (EFS) ausgeführt werden. Unten im Dashboard zeigen drei neue Karten Einsparmöglichkeiten nach Amazon-Speicherdienst an – EBS, FSx für Windows File Server und EFS. Auf allen Karten können Sie die Einsparmöglichkeiten detaillierter erkunden.

Anhand der FSx for ONTAP-Schutzabdeckungskarte und der Integritätskarte für Replikationsbeziehungen können Sie prüfen, ob Ihre FSx for ONTAP-Dateisysteme teilweise geschützte Volumes enthalten und Probleme mit Replikationsbeziehungen untersuchen. In beiden Fällen können Sie Maßnahmen zur Behebung der Probleme ergreifen.



==== Verbesserungen der Registerkarte „Lautstärke“

Die Registerkarte „Volumes“ in der Workload Factory-Konsole wurde erweitert, um eine umfassendere Ansicht Ihrer FSx for ONTAP-Dateisysteme zu bieten. Zu den Erweiterungen gehören neue Karten für SSD-Kapazität, Kapazitätspool und NetApp Autonomous Ransomware Protection mit KI (ARP/AI). Diese Karten fassen die Kapazitätsauslastung und den ARP/AI-Schutz für alle Volumes im Dateisystem zusammen.



==== Unterstützung für die zweite Generation von Amazon FSX für NetApp ONTAP-Filesystemen

Workload Factory unterstützt jetzt Amazon FSx für NetApp ONTAP-Dateisysteme der zweiten Generation. Sie können Dateisysteme der zweiten Generation in der Workload Factory-Konsole erstellen, verwalten und überwachen. Alle neuen kommerziellen Regionen werden unterstützt.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Erstellen Sie ein Dateisystem der zweiten Generation in der Workload Factory"]



==== FlexVol-Volume-Unterstützung zum Neuausgleich der Volume-Kapazität

FlexVol-Volumes sind in der Workload Factory-Konsole erkennbar. Sie können die Balance Ihrer FlexVol-Volumes überprüfen und die Kapazität neu verteilen, wenn sich im Laufe der Zeit durch das Hinzufügen neuer Dateien und Dateiwachstum Ungleichgewichte ergeben.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["Neuausgleich der Kapazität eines FlexVol-Volumes"]



==== Terminologie-Update

Der Begriff „Autonomous Ransomware Protection“ (ARP) wurde in der Workload Factory-Konsole in „NetApp Autonomous Ransomware Protection with AI“ (ARP/AI) aktualisiert.



==== ARP/AI standardmäßig für neue Volumes aktiviert

Wenn Sie in der Workload Factory-Konsole ein neues Volume erstellen, ist NetApp Autonomous Ransomware Protection mit KI (ARP/AI) standardmäßig aktiviert, sofern das Dateisystem über eine ARP/AI-Richtlinie verfügt. Das bedeutet, dass das Volume mithilfe KI-gestützter Erkennungs- und Reaktionsfunktionen automatisch vor Ransomware-Angriffen geschützt ist.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Erstellen eines Volumes in der Workload Factory"]



==== Replikationsunterstützung für unveränderliche Dateien

Workload Factory unterstützt die Replikation unveränderlicher Volumes von einem FSx for ONTAP-System auf ein anderes FSx for ONTAP-Dateisystem, um kritische Daten vor versehentlichem Löschen oder böswilligen Angriffen wie Ransomware zu schützen. Das Zielvolume und sein Host-Dateisystem sind unveränderlich bzw. gesperrt, und Daten im Zieldateisystem können bis zum Ende der Aufbewahrungsfrist weder geändert noch entfernt werden.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Erfahren Sie, wie Sie eine Replikationsbeziehung erstellen"]



==== Verwalten der IAM-Ausführungsrolle und -Berechtigungen während der Linkerstellung

Sie können jetzt die IAM-Ausführungsrolle und die zugehörige Berechtigungsrichtlinie verwalten, indem Sie einen Link in der Workload Factory-Konsole erstellen. Ein Link stellt die Verbindung zwischen Ihrem Workload Factory-Konto und einem oder mehreren FSx for ONTAP-Dateisystemen her. Sie haben zwei Möglichkeiten, die IAM-Ausführungsrolle und die Linkberechtigungen zuzuweisen: automatisch oder benutzerdefiniert. Durch die Verwaltung der Ausführungsrolle und der zugehörigen Berechtigungsrichtlinie in der Workload Factory müssen Sie keinen Drittanbietercode mehr verwenden.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Stellen Sie über einen Lambda-Link eine Verbindung zu einem FSX für ONTAP-Dateisystem her"]



=== VMware-Workloads



==== Einführung der Migrationsberater-Unterstützung für Amazon Elastic VMWare Service

Die BlueXP Workload Factory für VMware unterstützt jetzt Amazon Elastic VMware Service. Mit dem Migration Advisor können Sie Ihre lokalen VMware-Workloads schnell zu Amazon Elastic VMware Service migrieren. Das optimiert die Kosten und ermöglicht Ihnen mehr Kontrolle über Ihre VMware-Umgebung, ohne Ihre Anwendungen umgestalten oder auf eine neue Plattform umstellen zu müssen.

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["Erstellen Sie einen Bereitstellungsplan für Amazon EVS mit dem Migrationsberater"]



=== GenAI-Workloads



==== Unterstützung für Datenquellen, die auf generischen NFS/SMB-Dateisystemen gehostet werden

Sie können jetzt eine Datenquelle aus einer generischen SMB- oder NFS-Freigabe hinzufügen. Dadurch können Sie Dateien einbeziehen, die auf Volumes gespeichert sind, die von anderen Dateisystemen als Amazon FSx für NetApp ONTAP gehostet werden.

https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["Hinzufügen von Datenquellen zu einer Wissensdatenbank"]

https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html#add-data-sources-to-the-connector["Hinzufügen von Datenquellen zu einem Connector"]



=== Einrichtung und Administration



==== Berechtigungsaktualisierung für Datenbanken

Die folgende Berechtigung ist jetzt im _schreibgeschützten_ Modus für Datenbanken verfügbar:  `cloudwatch:GetMetricData` .

https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Änderungsprotokoll für Berechtigungen"]



==== Unterstützung des BlueXP Workload Factory-Benachrichtigungsdienstes

Der Benachrichtigungsdienst der BlueXP Workload Factory ermöglicht es der Workload Factory, Benachrichtigungen an den BlueXP-Warndienst oder an ein Amazon SNS-Thema zu senden. An BlueXP-Warnmeldungen gesendete Benachrichtigungen werden im BlueXP-Warnmeldungsbereich angezeigt. Wenn die Workload Factory Benachrichtigungen an ein Amazon SNS-Thema veröffentlicht, erhalten Abonnenten des Themas (z. B. Benutzer oder andere Anwendungen) die Benachrichtigungen an den für das Thema konfigurierten Endpunkten (z. B. per E-Mail oder SMS).

https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Konfigurieren Sie die Benachrichtigungen der BlueXP-Workload-Factory"]



== 1 2025-06-16



=== Arbeitslasten der Bauarbeiter



==== Klonunterstützung

Sie können jetzt ein Projekt in der BlueXP Workload Factory für Builder klonen. Beim Klonen eines Projekts erstellt Builder aus einem Snapshot ein neues Projekt mit der gleichen Konfiguration wie das Original. Das Klonen ist nützlich, um schnell ähnliche Projekte zu erstellen oder zu Testzwecken. Sie können den neuen Projektklon mounten, indem Sie den Anweisungen in Builder folgen.

https://docs.netapp.com/us-en/workload-builders/version-projects.html["Verwalten Sie Versionen der BlueXP-Workload-Factory für Builder-Projekte"]



== 1 2025-06-08



=== Amazon FSX für NetApp ONTAP



==== Neue, gut strukturierte Analyse und Unterstützung zur Behebung von Problemen

Das automatische Kapazitätsmanagement für FSx für ONTAP-Dateisysteme ist jetzt als Konfigurationsanalyse im gut strukturierten Status-Dashboard enthalten.

Darüber hinaus unterstützt Workload Factory jetzt die Behebung der folgenden Konfigurationsprobleme:

* Schwellenwert für SSD-Kapazität
* Daten-Tiering
* Geplante lokale Snapshots
* FSx für ONTAP-Backups
* Remote-Datenreplizierung
* Storage-Effizienz
* Automatisches Kapazitätsmanagement


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Beheben von Konfigurationsproblemen"]



== 1 2025-06-03



=== Datenbank-Workloads



==== PostgreSQL- und Oracle-Erkennung

Sie können jetzt die Instanzen, die PostgreSQL-Serverdatenbanken und Oracle-Datenbankbereitstellungen in Ihrem AWS-Konto ausführen, in der Workload Factory-Konsole ermitteln. Erkannte Instanzen werden im Datenbankinventar angezeigt.



==== Aktualisierte Terminologie „Optimierung“

Workload Factory wurde früher als „Optimierung“ bezeichnet und verwendet jetzt „Well-Architected Issues“ und „Well-Architected Status“, um die Analyse von Datenbankkonfigurationen zu beschreiben, und „Fix“, um Abhilfemaßnahmen für Möglichkeiten zur Verbesserung von Datenbankkonfigurationen zu beschreiben, um Best-Practice-Empfehlungen zu erfüllen.

link:https://docs.netapp.com/us-en/workload-databases/optimize-overview.html["Konfigurationsanalyse für Datenbankumgebungen in der Workload Factory"]



==== Verbessertes Onboarding für Instanzen

Anstelle der Begriffe „unerkannt“, „unverwaltet“ oder „verwaltet“ für die Instanzverwaltung verwendet Workload Factory jetzt „Registrieren“ für das Onboarding von Instanzen. Der neue Registrierungsprozess umfasst die Authentifizierung und Vorbereitung von Instanzen, sodass Sie Ressourcen in Ihren Datenbankkonfigurationen in der Workload Factory-Konsole erstellen, überwachen, analysieren und reparieren können. Der Vorbereitungsschritt im Registrierungsprozess zeigt an, ob Ihre Instanzen für die Verwaltung bereit sind.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["Instanzmanagement"]



=== GenAI-Workloads



==== Tracker zur Überwachung und Nachverfolgung von Vorgängen verfügbar

Die Tracker-Überwachungsfunktion ist jetzt in GenAI verfügbar. Mit Tracker können Sie den Fortschritt und Status ausstehender, laufender und abgeschlossener Vorgänge überwachen und verfolgen, Details zu Vorgangsaufgaben und Unteraufgaben überprüfen, Probleme oder Fehler diagnostizieren, Parameter für fehlgeschlagene Vorgänge bearbeiten und fehlgeschlagene Vorgänge wiederholen.

link:https://docs.netapp.com/us-en/workload-genai/general/monitor-operations.html["Überwachen Sie Workload-Vorgänge mit Tracker in der BlueXP-Workload-Factory"]



==== Auswählen eines Reranking-Modells für eine Wissensdatenbank

Sie können jetzt die Relevanz neu bewerteter Abfrageergebnisse erhöhen, indem Sie ein bestimmtes Reranking-Modell für die Verwendung mit einer Wissensdatenbank auswählen. GenAI unterstützt die Modelle Cohere Rerank und Amazon Rerank.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Einrichtung einer GenAI Knowledge Base"]



== 1 2025-05-04



=== Datenbank-Workloads



==== Dashboard-Verbesserungen

* Kunden- und regionsübergreifende Ansichten sind verfügbar, wenn Sie in der BlueXP  Workload Factory-Konsole zwischen den Registerkarten navigieren. Die neuen Ansichten verbessern das Ressourcenmanagement, die Überwachung und die Optimierung.
* Über die Kachel *potenzielle Einsparungen* im Dashboard können Sie schnell überprüfen, was Sie sparen könnten, indem Sie vom Amazon Elastic Block Store oder Amazon FSX for Windows File Server zu FSX for ONTAP wechseln.




==== Ad-hoc-Scans für Datenbankkonfigurationen verfügbar

Die BlueXP -Workload-Fabrik für Datenbanken scannt gemanagte Microsoft SQL Server-Instanzen automatisch mit FSX für ONTAP Storage auf potenzielle Konfigurationsprobleme. Zusätzlich zum täglichen Scan können Sie jetzt jederzeit scannen.



==== Entfernung von Beurteilungsunterlagen vor Ort

Nachdem Sie die Einsparungen für einen lokalen Microsoft SQL Server-Host untersucht haben, haben Sie die Möglichkeit, den lokalen Host-Datensatz aus der BlueXP  Workload Factory zu entfernen.



==== Optimierungsverbesserungen



===== Klonbereinigung

Die Bewertung und Korrektur der Klonbereinigung identifiziert und managt alte und teure Klone. Klone, die älter als 60 Tage sind, können aktualisiert oder aus der BlueXP -Workload-Werkseinstellungen gelöscht werden.



===== Verschieben und Verwerfen der Konfigurationsanalyse

Einige Konfigurationen gelten möglicherweise nicht für Ihre Datenbankumgebungen. Sie haben jetzt die Möglichkeit, eine bestimmte Konfigurationsanalyse um 30 Tage zu verschieben oder die Analyse zu verwerfen.



==== Entfernung von Beurteilungsunterlagen vor Ort

Nachdem Sie die Einsparungen für einen lokalen Microsoft SQL Server-Host untersucht haben, haben Sie die Möglichkeit, den lokalen Host-Datensatz aus der BlueXP  Workload Factory zu entfernen.



==== Terminologie für Berechtigungen wurde aktualisiert

In der Benutzeroberfläche und Dokumentation der Workload Factory wird jetzt „schreibgeschützt“ für Leseberechtigungen und „Lesen/Schreiben“ für automatisierte Berechtigungen verwendet.



=== VMware-Workloads



==== Verbesserungen bei Amazon EC2 Migration Advisor

Diese Version der BlueXP  Workload-Farm für VMware umfasst folgende Verbesserungen zur Nutzung des Amazon EC2 Migrationsberaters:

*Einblicke in die NetApp-Dateninfrastruktur als Datenquelle*: Workload Factory stellt jetzt eine direkte Verbindung mit NetApp Data Infrastructure Insights her, um VMware Implementierungsinformationen zu erfassen, wenn Sie den Data Collector des EC2 Migration Advisor verwenden.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Erstellen eines Implementierungsplans für Amazon EC2 mithilfe des Migrationsberaters"]



==== Terminologie für Berechtigungen wurde aktualisiert

In der Benutzeroberfläche und Dokumentation der Workload Factory wird jetzt „schreibgeschützt“ für Leseberechtigungen und „Lesen/Schreiben“ für automatisierte Berechtigungen verwendet.



=== GenAI-Workloads



==== Support für NetApp Connector für Amazon Q Business

Diese Version von GenAI bietet Unterstützung für NetApp Connector für Amazon Q Business und ermöglicht Ihnen die Erstellung von Konnektoren für Amazon Q Business. Nutzen Sie den Amazon Q Business KI-Assistenten schnell und einfach mit einer geringeren Erstkonfiguration als mit dem Aufbau einer GenAI Knowledge Base für Amazon Bedrock.

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["Erstellen Sie einen NetApp Connector für Amazon Q Business"]



==== Verbesserter Support für Chatmodelle

GenAI unterstützt jetzt die folgenden zusätzlichen Chatmodelle für Wissensdatenbanken:

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Mistral KI-Modelle"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Amazon Titan Textmodelle"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Meta Llama Modelle"^]
* link:https://docs.ai21.com/["Jamba 1.5 Modelle"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Co-here Command-Modelle"^]
* link:https://aws.amazon.com/bedrock/deepseek/["Deepseek-Modelle"^]


GenAI unterstützt die Modelle von jedem Provider, die von Amazon Bedrock unterstützt werden: link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Unterstützte Basismodelle in Amazon Bedrock"^]

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Einrichtung einer GenAI Knowledge Base"]



==== Terminologie für Berechtigungen wurde aktualisiert

In der Benutzeroberfläche und Dokumentation der Workload Factory wird jetzt „schreibgeschützt“ für Leseberechtigungen und „Lesen/Schreiben“ für automatisierte Berechtigungen verwendet.



=== Einrichtung und Administration



==== Autocomplete-Unterstützung für CloudShell

Wenn Sie BlueXP  Workload Factory CloudShell verwenden, können Sie einen Befehl eingeben und die Tabulatortaste drücken, um die verfügbaren Optionen anzuzeigen. Wenn mehrere Möglichkeiten vorhanden sind, zeigt die CLI eine Liste mit Vorschlägen an. Diese Funktion steigert die Produktivität, indem Fehler minimiert und die Befehlsausführung beschleunigt wird.



==== Terminologie für Berechtigungen wurde aktualisiert

In der Benutzeroberfläche und Dokumentation der Workload Factory wird jetzt „schreibgeschützt“ für Leseberechtigungen und „Lesen/Schreiben“ für automatisierte Berechtigungen verwendet.



=== Arbeitslasten der Bauarbeiter



==== Terminologie für Berechtigungen wurde aktualisiert

In der Benutzeroberfläche und Dokumentation der Workload Factory wird jetzt „schreibgeschützt“ für Leseberechtigungen und „Lesen/Schreiben“ für automatisierte Berechtigungen verwendet.



== 1 2025-03-30



=== Einrichtung und Administration



==== CloudShell meldet AI-generierte Fehlermeldungen für ONTAP-CLI-Befehle

Bei der Verwendung von CloudShell können Sie jedes Mal, wenn Sie einen ONTAP-CLI-Befehl ausgeben und ein Fehler auftritt, AI-generierte Fehlermeldungen erhalten, die eine Beschreibung des Fehlers, die Ursache des Fehlers und eine detaillierte Lösung enthalten.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Verwenden Sie CloudShell"]



==== iam:SimulatePermissionPolicy-Berechtigungsaktualisierung

Sie können jetzt die Berechtigung über die Konsole für die Werkseinstellungen managen `iam:SimulatePrincipalPolicy`, wenn Sie zusätzliche AWS-Kontoinformationen hinzufügen oder eine neue Workload-Funktion hinzufügen, z. B. den GenAI-Workload.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Änderungsprotokoll für Berechtigungen"]



== 1 2024-12-01



=== Arbeitslasten der Bauarbeiter



==== Ursprüngliche Version des Builders-Workloads

Die BlueXP  Workload Factory for Builders vereinfacht die Nutzung und den Zugriff auf Softwareversionen, sodass keine benutzerdefinierten Tools oder Skripte erforderlich sind. Sie können Softwareversionen als in Perforce Helix Core integrierte, sofort-Clones als komfortable Arbeitsumgebung für Ihre Entwicklungsprozesse nutzen und so Zeit und Ressourcen sparen.

Die erste Version beinhaltet die Möglichkeit, Projekte und Arbeitsbereiche zu verwalten und Aktionen mit Codebox zu automatisieren. Sie können auch Builders mit Perforce Helix Core integrieren, so dass Sie verschiedene Versionen jedes Projekts verwalten und schnell zwischen ihnen wechseln können.
