---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: Informieren Sie sich über die neuesten Änderungen an den Workloads, die Teil der NetApp Workload Factory sind. 
---
= Aktuelle Änderungen in der NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Informieren Sie sich über die neuesten Änderungen an den Workloads, die Teil der NetApp Workload Factory sind.



== 06. April 2026



=== Amazon FSX für NetApp ONTAP



==== Gut strukturierte Analyse-Updates

Workload Factory analysiert Ihre FSx for ONTAP-Dateisysteme auf *inaktive NAS-Volumes*. Die Konfigurationsanalyse identifiziert nicht aktiv genutzte NAS-Volumes und empfiehlt Maßnahmen zur Optimierung der Speichernutzung und Kostensenkung.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implementieren Sie gut strukturierte FSx for ONTAP Dateisysteme"]



==== Journaltabellenfunktion für S3-Zugriffspunkte

Die Journaltabellenfunktion bietet eine Möglichkeit, den FSx ONTAP S3-Objektspeicher in großem Maßstab zu verwalten und ermöglicht es Ihnen, Benutzerzugriffsereignisse und Operationen an Objekten in Ihren Buckets einfach zu protokollieren. Mit Workload Factory können Sie automatische Scans Ihrer Buckets und S3-Tabellen einrichten, um eine Aufzeichnung der Ereignisse zu führen, die alle Objekte, deren Details und Benutzeraktionen anzeigt.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/setup-journal-table.html["Richten Sie die Journaltabelleninfrastruktur für NetApp Workload Factory ein."]



==== Unterstützung für die Verwaltung bestehender Initiatorgruppen

Workload Factory unterstützt die Verwaltung bestehender Initiatorgruppen. Sie können Blockgeräte und Host-Initiatoren hinzufügen oder entfernen, um Ihre bereitgestellte Workload termingerecht auszuliefern.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-storage.html["Blockspeicher in NetApp Workload Factory verwalten"]



==== Unterstützung für die Angabe des Aggregats für FlexVol volumes

Workload Factory unterstützt das Erstellen von FlexVol Volumes auf einem ausgewählten Aggregat. Dadurch können Sie die Kapazitäts- und Leistungslast auf alle Dateisystemressourcen verteilen.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Erstellen Sie ein FlexVol Volume in NetApp Workload Factory"]



=== Datenbank-Workloads



==== Gut konzipierte Analyse für Oracle

Die gut durchdachte Analyse umfasst die folgenden neuen Konfigurationen für Oracle:

* *Oracle Critical Patch Updates*: Bewertet fehlende Sicherheitspatches für unterstützte selbstverwaltete Oracle-Datenbankinstallationen.
* *Regionsübergreifende Replikation*: Prüft, ob die regionsübergreifende Replikation (CRR) für Ihre FSx for ONTAP Dateisysteme, die Oracle Datenbanken bedienen, aktiviert ist.
* *Applikationskonsistente Snapshots*: prüft, ob die Oracle Datenbank durch applikationskonsistente Snapshots mit NetApp SnapCenter geschützt ist.


link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementieren Sie gut strukturierte Datenbankkonfigurationen in Workload Factory"]



==== Einmalige Bewertung für Oracle

Workload Factory bietet jetzt eine einmalige Analyse Ihrer Oracle Datenbank-Bereitstellungen – wann immer Sie diese benötigen: bei Neuinstallationen, nach Migrationen, bei der Fehlerbehebung und mehr. Sie erhalten Empfehlungen zur Optimierung Ihrer Bereitstellungskonfigurationen und zur Einhaltung von Best Practices. Dies ist Ihre Gelegenheit, die well-architected Funktion zu nutzen, ohne sich vollständig auf den Einrichtungsprozess festlegen zu müssen. Sie können Ihre Datenbanken analysieren, ohne Anmeldeinformationen in Workload Factory zu speichern, Datenbankressourcen zu registrieren oder externe Verbindungen einzurichten.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Führen Sie eine einmalige Bewertung Ihrer Oracle-Datenbankbereitstellungen durch"]



==== Verbesserte Kosteneinsparungen für mehrere Oracle-Datenbanken

Wir haben die Kostenanalyse für Oracle optimiert, um eine konsolidierte Speicherlösung für mehrere lokale Oracle-Datenbanken auf einem FSx for ONTAP-Dateisystem bereitzustellen. Diese Konsolidierung optimiert die Speicherkosten, indem die Anzahl der für mehrere Datenbanken benötigten Dateisysteme reduziert wird, was zu höheren Kosteneinsparungen führt.

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["Entdecken Sie Einsparungen für erkannte Datenbanken auf Oracle On-Premises."]



=== Einrichtung und Administration



==== Neue Benachrichtigung für Storage

Der NetApp Workload Factory-Benachrichtigungsdienst umfasst die Benachrichtigung für NetApp Autonomous Ransomware Protection with AI (ARP/AI) für Storage.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Benachrichtigungen für NetApp Workload Factory"]



== 09. März 2026



=== VMware-Workloads



==== Einführung der Unterstützung für Migration Advisor für Google Cloud VMware Engine

NetApp Workload Factory unterstützt jetzt Google Cloud VMware Engine. Sie können Ihre lokalen VMware-Workloads zu Google Cloud VMware Engine migrieren, indem Sie Google Cloud NetApp Volumes als externe NFS-Datenspeicher verwenden. Dadurch werden die Kosten optimiert und Sie erhalten mehr Kontrolle über Ihre VMware-Umgebung, ohne Ihre Anwendungen refaktorisieren oder auf eine neue Plattform umstellen zu müssen.

Der Google Cloud VMware Engine Migrationsberater bietet:

* Automatisierte Dimensionierung und Auslegung von Google Cloud VMware Engine-Clustern mit Unterstützung für VE1- und VE2-Knotentypen
* VM-Layoutoptimierung zwischen internen vSAN-Datenspeichern und Google Cloud NetApp Volumes externen NFS-Datenspeichern.
* Detaillierter Kostenvergleich und TCO-Analyse zwischen reinen vSAN- und Google Cloud NetApp Volumes-basierten Konfigurationen.
* Unterstützung für die Servicelevel Standard, Premium und Extreme des Google Cloud NetApp Volumes.
* Infrastructure-as-Code-Bereitstellung mit Terraform für die automatisierte Bereitstellung.




== 02. März 2026



=== Datenbank-Workloads



==== Einmalige Bewertung für SQL Server

Workload Factory bietet jetzt eine einmalige Analyse Ihrer SQL Server Datenbankbereitstellungen – wann immer Sie diese benötigen: bei neuen Bereitstellungen, nach der Migration, bei der Fehlerbehebung und mehr. Sie erhalten Empfehlungen zur Optimierung Ihrer Bereitstellungskonfigurationen und zur Einhaltung von Best Practices. Dies ist Ihre Gelegenheit, die well-architected Funktion zu nutzen, ohne sich vollständig auf den Einrichtungsprozess festlegen zu müssen. Sie können Ihre Datenbanken analysieren, ohne Anmeldeinformationen in Workload Factory zu speichern, Datenbankressourcen zu registrieren oder externe Verbindungen einzurichten.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Führen Sie eine einmalige Bewertung Ihrer Datenbankbereitstellungen durch."]



==== Registrierungsunterstützung für Always On-Verfügbarkeitsgruppen auf Microsoft SQL Server und Data Guard auf Oracle

Sie können nun Microsoft SQL Server-Instanzen mit dem Always On-Verfügbarkeitsgruppenmodell (AOAG) und Oracle-Datenbanken mit dem Data Guard-Bereitstellungsmodell in der NetApp Workload Factory-Datenbank-Workload erkennen und registrieren. Diese Erweiterung ermöglicht eine optimierte Verwaltung von SQL Server- und Oracle-Ressourcen innerhalb der Workload Factory-Konsole.

Nach der Registrierung Ihrer AOAG-Instanzen und Data Guard Datenbanken können Sie die verschiedenen Funktionen in Workload Factory for Databases nutzen, wie das Anzeigen von Ressourcendetails und das Analysieren von Fehlerprotokollen.

Workload Factory for Databases unterstützt auch die Well-Architected-Analyse für Microsoft SQL Server-Instanzen mit dem AOAG-Bereitstellungsmodell. Sie können die Konfigurationen Ihrer SQL Server-Instanzen in einer Verfügbarkeitsgruppe analysieren und Empfehlungen zur Optimierung Ihrer Bereitstellungskonfigurationen und zur Einhaltung bewährter Verfahren erhalten. Registrieren Sie Ihre AOAG-Instanzen, um diese Funktion zu aktivieren.

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html#register-a-sql-server-instance["Ressourcen in Workload Factory for Databases registrieren"]



==== Gut konzipierte Analyse für Oracle

Die gut strukturierte Analyse umfasst *Betriebssystem-Patches* für Oracle, um zu überprüfen, ob Sie die neuesten Patches auf dem Betriebssystem haben, und Ihnen mitzuteilen, wie Sie diese installieren können.

Darüber hinaus benachrichtigt Sie die Well-Architected-Analyse für Oracle, wenn eine Konfiguration wie Storage-Layout Abhängigkeiten von anderen Konfigurationen hat. Die Benachrichtigung teilt Ihnen mit, welche Maßnahmen zur Optimierung verknüpfter Konfigurationen erforderlich sind, damit alle Empfehlungen, die wir bereitstellen, optimal sind.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementieren Sie gut strukturierte Datenbankkonfigurationen in Workload Factory"]



==== Kostenanalyse und Migrationsplanung für Oracle-On-Premises-Datenbankumgebungen

Workload Factory for Databases analysiert und unterstützt Sie jetzt bei der Planung der Oracle On-Premises-Datenbankmigration zu Amazon FSx for NetApp ONTAP. Mit dem Kostenrechner können Sie die Kosten für den Betrieb Ihrer lokalen Oracle-Datenbankumgebung in der Cloud abschätzen und Empfehlungen für die Migration Ihrer lokalen Datenbankumgebung in die Cloud einsehen.

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html["Entdecken Sie Einsparmöglichkeiten für lokale Datenbankumgebungen"]



==== Neues „Ask Me“-Lesezeichen in Workload Factory verfügbar

Wir haben auf jedem Bildschirm in der Workload Factory-Konsole ein neues Ask Me-Lesezeichen hinzugefügt. Diese Verbesserung macht es für Sie einfacher und schneller, auf Ask Me zuzugreifen, wann immer Sie Hilfe benötigen. Ask Me ist unser KI-Assistent, der es Ihnen ermöglicht, Fragen zu Ihren eigenen Workload-Umgebungen zu stellen, personalisierte Einblicke direkt aus Ihrer Umgebung zu erhalten und auf frühere Konversationen zuzugreifen.

Sie können Ask Me von jeder Seite aus öffnen, indem Sie auf das neue Lesezeichen klicken. Es startet Ask Me in einem Seitenbereich, ohne Ihre aktuelle Arbeit zu unterbrechen, und bietet schnelle Erklärungen und Empfehlungen zu dem, was Sie gerade tun.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["Erfahren Sie mehr über Ask Me"^]



== 01. März 2026



=== Amazon FSX für NetApp ONTAP



==== Gut strukturierte Analyse-Updates

Workload Factory analysiert Ihre FSx for ONTAP -Dateisysteme für die folgenden Konfigurationen:

* Unterausgelastete SSD-Kapazität: Prüft, ob die SSD-Kapazitätsebene unterausgelastet ist, und empfiehlt, die SSD-Kapazität zu verringern, um die Kosten zu optimieren.
* Planen Sie Volume-Backups: Workload Factory verbessert die Konfigurationsempfehlung und bietet Optionen zum Aktivieren von FSx for ONTAP backup oder AWS Backup. FSx for ONTAP backup wendet eine Standardrichtlinie auf alle Volumes in einem Dateisystem an und erstellt tägliche Backups, die bis zu 90 Tage aufbewahrt werden. AWS Backup ermöglicht es Ihnen, für jedes Volume im Backup-Plan unterschiedliche Aufbewahrungsfristen auszuwählen.




==== Workload Factory unterstützt KI- und ML-Anwendungsfälle für die Replikation

Workload Factory unterstützt die Replikation von On-Premises ONTAP-Daten zu Amazon FSx for NetApp ONTAP und die Erstellung von S3-Zugriffspunkten für AWS Artificial Intelligence (AI) und Machine Learning (ML) Services, um AI/ML-Workflows zu beschleunigen.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Replizieren Sie On-Premises-Daten für KI- und ML-Anwendungsfälle"]



==== Bearbeiten vorhandener S3-Zugangspunkte

Sie können den Benutzer und den Benutzertyp für einen vorhandenen, mit einem Volume verbundenen S3-Zugriffspunkt ändern. Sie können außerdem Metadaten für den Zugriffspunkt aktivieren oder deaktivieren.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/edit-s3-access-points.html["Bearbeiten Sie S3-Zugriffspunkte in NetApp Workload Factory"]



==== Blockspeicherdiagramm hinzugefügt

Wenn Sie Blockspeicher verwenden, können Sie das Blockspeicherdiagramm anzeigen, um zu visualisieren, wie Blockgeräte mit Knoten und Initiatorgruppen verbunden sind. Das Diagramm hilft Ihnen, Ihren Blockspeicher zu verstehen und zu verwalten.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-storage.html["Blockspeicher in NetApp Workload Factory verwalten"]



==== Aktualisierung der automatischen Kapazitätsmanagement-Funktion

Dieses Update teilt die Funktion in zwei separate Funktionen auf: automatisches Kapazitätsmanagement und Kapazitätsbenachrichtigungen.

Das automatische Kapazitätsmanagement fügt automatisch Dateisystemkapazität hinzu oder entfernt sie, um eine optimale Leistung aufrechtzuerhalten. Neue Optionen umfassen inkrementelle und adaptive Modi. Im inkrementellen Modus erhöht das System die Kapazität an Schwellenwerten um einen festen Betrag; im adaptiven Modus verwendet es historische Daten, um die Kapazität vorherzusagen und anzupassen.

Kapazitätsbenachrichtigungen informieren Sie, wann immer eine Kapazitätsanpassung erfolgt und wenn Dateisysteme festgelegte Grenzwerte erreichen, sodass Sie den Storage verwalten können, bevor Probleme auftreten.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["Erfahren Sie mehr über automatisches Kapazitätsmanagement und Kapazitätsbenachrichtigungen in NetApp Workload Factory"]



==== Neues „Ask Me“-Lesezeichen in Workload Factory verfügbar

Wir haben auf jedem Bildschirm in der Workload Factory-Konsole ein neues Ask Me-Lesezeichen hinzugefügt. Diese Verbesserung macht es für Sie einfacher und schneller, auf Ask Me zuzugreifen, wann immer Sie Hilfe benötigen. Ask Me ist unser KI-Assistent. Sie können Fragen zu Ihren Workload-Umgebungen stellen, personalisierte Einblicke erhalten und frühere Konversationen überprüfen.

Sie können Ask Me von jeder Seite aus öffnen, indem Sie auf das neue Lesezeichen klicken. Es startet Ask Me in einem Seitenbereich, ohne Ihre aktuelle Arbeit zu unterbrechen, und bietet schnelle Erklärungen und Empfehlungen zu dem, was Sie gerade tun.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["Erfahren Sie mehr über Ask Me"^]



=== VMware-Workloads



==== Neues „Ask Me“-Lesezeichen in Workload Factory verfügbar

Wir haben auf jedem Bildschirm in der Workload Factory-Konsole ein neues Ask Me-Lesezeichen hinzugefügt. Diese Verbesserung macht es für Sie einfacher und schneller, auf Ask Me zuzugreifen, wann immer Sie Hilfe benötigen. Ask Me ist unser KI-Assistent, der es Ihnen ermöglicht, Fragen zu Ihren eigenen Workload-Umgebungen zu stellen, personalisierte Einblicke direkt aus Ihrer Umgebung zu erhalten und auf frühere Konversationen zuzugreifen.

Sie können Ask Me von jeder Seite aus öffnen, indem Sie auf das neue Lesezeichen klicken. Es startet Ask Me in einem Seitenbereich, ohne Ihre aktuelle Arbeit zu unterbrechen, und bietet schnelle Erklärungen und Empfehlungen zu dem, was Sie gerade tun.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["Erfahren Sie mehr über Ask Me"^]



=== Einrichtung und Administration



==== Neues „Ask Me“-Lesezeichen in Workload Factory verfügbar

Wir haben auf jedem Bildschirm in der Workload Factory-Konsole ein neues Ask Me-Lesezeichen hinzugefügt. Diese Verbesserung macht es für Sie einfacher und schneller, auf Ask Me zuzugreifen, wann immer Sie Hilfe benötigen. Ask Me ist unser KI-Assistent, der es Ihnen ermöglicht, Fragen zu Ihren eigenen Workload-Umgebungen zu stellen, personalisierte Einblicke direkt aus Ihrer Umgebung zu erhalten und auf frühere Konversationen zuzugreifen.

Sie können Ask Me von jeder Seite aus öffnen, indem Sie auf das neue Lesezeichen klicken. Ask Me wird in einem Seitenbereich geöffnet, ohne Ihre aktuelle Arbeit zu unterbrechen, und bietet schnelle Erklärungen und Empfehlungen zu dem, was Sie gerade tun.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["Erfahren Sie mehr über Ask Me"]



=== EDA-Workloads



==== Übersichts-Dashboard für EDA-Speicherverwaltung

Als IT-Administrator, der Dutzende von FSx for ONTAP Dateisystemen verwaltet, können Sie mithilfe des Übersichts-Dashboards häufige betriebliche Fragen zum Clusterzustand, zur Auslastung und zur Volume-Platzierung beantworten.

Das Übersichts-Dashboard umfasst:

* *Cluster-Gesundheitsstatus*: Informationen, die oben im Dashboard zusammengefasst sind und Leistungs-, Kapazitäts-, Verfügbarkeits-, Schutz- und Sicherheitsereignisse in Ihren Clustern hervorheben.
* *Clusters table*: Eine durchsuchbare, filterbare und paginierte Tabelle, die SSD-Kapazität, Kapazitätspool und Durchsatzmetriken pro Cluster anzeigt, mit Unterstützung für Spaltenanpassung und CSV-Export.


Das bisherige Haupt-Dashboard ist jetzt im Reiter *Projekt* zu finden. Die EDA-Reiter sind nun wie folgt geordnet: Übersicht, Latenz, Projekt, CI/CD.

https://docs.netapp.com/us-en/workload-eda/task-use-overview-dashboard.html["Erfahren Sie mehr über das Übersichtsdashboard"^].



==== Automatisierte Latenzanalyse

Die Latenzanalyse umfasst nun auch eine automatisierte Basisanalyse. Wenn Latenzereignisse erkannt werden, analysiert das System automatisch die ONTAP QoS Delay Center-Metriken, um die Ursache der Latenzprobleme zu identifizieren.

Die Basisanalyse wertet QoS-Richtlinien, Festplattenleistung, Netzwerkprobleme und Clusterkonfigurationen aus, um in der Spalte Details der Tabelle der Latenzereignisse sofortige Einblicke zu liefern.

https://docs.netapp.com/us-en/workload-eda/task-monitor-latency.html#understanding-basic-analysis["Erfahren Sie mehr über die grundlegende Latenzanalyse"^].



==== Neues „Ask Me“-Lesezeichen in Workload Factory verfügbar

Wir haben auf jedem Bildschirm in der Workload Factory-Konsole ein neues Ask Me-Lesezeichen hinzugefügt. Diese Verbesserung macht es für Sie einfacher und schneller, auf Ask Me zuzugreifen, wann immer Sie Hilfe benötigen. Ask Me ist unser KI-Assistent, der es Ihnen ermöglicht, Fragen zu Ihren eigenen Workload-Umgebungen zu stellen, personalisierte Einblicke direkt aus Ihrer Umgebung zu erhalten und auf frühere Konversationen zuzugreifen.

Sie können Ask Me von jeder Seite aus öffnen, indem Sie auf das neue Lesezeichen klicken. Es startet Ask Me in einem Seitenbereich, ohne Ihre aktuelle Arbeit zu unterbrechen, und bietet schnelle Erklärungen und Empfehlungen zu dem, was Sie gerade tun.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["Erfahren Sie mehr über Ask Me"^]



== 16. Februar 2026



=== Amazon FSX für NetApp ONTAP



==== Unterstützung für die Migration von Storage-VMs

NetApp Workload Factory unterstützt jetzt die Migration für Speicher-VMs. Diese Funktion ermöglicht die Migration von ONTAP-Speichersystemdaten und -konfigurationen von lokalen ONTAP-Systemen oder FSx for ONTAP-Dateisystemen der ersten Generation auf FSx for ONTAP-Dateisysteme der zweiten Generation. Sie können Speicher-VM-Daten und -Konfigurationseinstellungen replizieren, um mit minimalen Ausfallzeiten und geringen Beeinträchtigungen für Benutzer und Anwendungen auf das neue Dateisystem zu migrieren.

Um diese Funktion zu nutzen, link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["eine Replikationsbeziehung erstellen"] und wählen Sie *Migration* als Anwendungsfall aus. Um den Migrationsprozess abzuschließen, müssen Sie link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html#cut-over-replication-for-migration-use-cases["Schalten Sie die Storage-VM und ihre replizierten Volumes um"] sofort ausführen, um Daten und Konfigurationseinstellungen der Storage-VMs dauerhaft auf das Ziel-FSx for ONTAP-Dateisystem zu migrieren.



== 02. Februar 2026



=== Datenbank-Workloads



==== Verbesserte Kosteneinsparungen für mehrere Datenbank-Hosts auf Microsoft SQL Server on-premises

Die Kostenanalyse für die lokale Speicherung von Microsoft SQL Server wurde verbessert, um eine konsolidierte Speicherlösung für mehrere Datenbankhosts auf einem FSx for ONTAP-Dateisystem bereitzustellen. Diese Konsolidierung optimiert die Speicherkosten, indem die Anzahl der für mehrere Datenbankhosts erforderlichen Dateisysteme reduziert wird, was zu verbesserten Kosteneinsparungen führt.

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["Entdecken Sie die Einsparungen für erkannte Hosts auf Microsoft SQL Server on-premises"]



==== Gut konzipierte Analyse für Oracle

Die gut strukturierte Analyse umfasst vier neue Teilbewertungen für die Speicherkonfigurationsanalyse für Oracle: dNFS-Aktivierung, dNFS konsistente IP-Auflösung, dNFS Konfigurationsdatei und dNFS `nosharecache`. Diese Bewertungen beziehen sich auf die Aktivierung und Einrichtung von Direct NFS (dNFS) für Ihre Oracle-Umgebung, das den Host-NFS-Client umgeht und NFS-Dateioperationen direkt auf einem NFS-Server ausführt, wodurch die E/A-Leistung verbessert und die Last auf dem Host und dem Speichersystem verringert wird, da die E/A effizienter ausgeführt wird.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementieren Sie gut strukturierte Datenbankkonfigurationen in Workload Factory"]



== 01. Februar 2026



=== Amazon FSX für NetApp ONTAP



==== Die Startseite enthält gut strukturierte Probleme und EMS-Ereignisse für Storage

Die NetApp Workload Factory-Startseite enthält eine Fokus-Kachel, auf der gut-architektierte Probleme und FSx for ONTAP Emergency Management System (EMS)-Ereignisse für Ihre Workloads angezeigt werden. Von dort aus können Sie zur Storage-Workload navigieren, um den gut-architektierte Status oder die Ereignisse aller FSx for ONTAP-Dateisysteme in Ihrer Speicherumgebung anzuzeigen.



==== Unterstützung für die lokale Datenreplizierung mithilfe eines S3-Zugriffspunkts

Workload Factory unterstützt die Replikation lokaler ONTAP-Daten in die Cloud zur Integration mit AWS GenAI, ML und Analysen. Sie können Ihre lokalen Daten mithilfe eines S3-Zugriffspunkts auf ein NFS- oder SMB/CIFS-Volume replizieren.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Replizieren Sie lokale Daten mithilfe eines S3-Zugriffspunkts"]



==== S3-Zugriffspunktverbesserungen in Storage

Mehrere Verbesserungen wurden an den Funktionen zur Verwaltung von S3-Zugriffspunkten in der Storage-Workload für NetApp Workload Factory vorgenommen. Sie können Netzwerkkonfigurationsdetails für Ihre S3-Zugriffspunkte eingeben und S3-Zugriffspunkt-Tags hinzufügen. Weitere Verbesserungen umfassen die Möglichkeit, S3-Bucket-Details anzuzeigen und zusätzliche Aktionen zur Verwaltung von S3-Zugriffspunkten durchzuführen.



===== S3-Bucket-Details verfügbar in Storage

Die neue Inventartabelle scannt automatisch Ihre AWS S3-Buckets und füllt die S3-Tabellen, um Ihnen eine übersichtliche Momentaufnahme aller Objekte, ihrer Metadaten, Attribute und Tags zu liefern. Der Zugriff auf diese Details hilft Ihnen, die Kontrolle, Transparenz und das Vertrauen in die Daten, für die Sie verantwortlich sind, zu wahren, während der Betriebsaufwand reduziert wird. Sie können die Funktion beim Erstellen und Zuordnen von S3-Zugriffspunkten oder beim Bearbeiten bestehender Zugriffspunkte aktivieren.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-s3-access-point.html["Erstellen und Zuordnen eines S3-Zugriffspunkts für ein Volume in NetApp Workload Factory"]



===== Zusätzliche Verwaltungsoperationen für S3 access points

NetApp Workload Factory bietet zusätzliche Verwaltungsoperationen für S3-Zugriffspunkte. Sie können Zugriffspunktdetails anzeigen, bestehende S3-Zugriffspunkte bearbeiten sowie S3-Zugriffspunkt-Tags über die NetApp Workload Factory-Oberfläche hinzufügen oder entfernen, wodurch Ihre Aufgaben im Bereich der Objektspeicherverwaltung optimiert werden.



==== Gut strukturierte Analyse-Updates

Workload Factory analysiert Ihre FSx for ONTAP -Dateisysteme für die folgenden Konfigurationen:

* Optimiert die Cache-Volume-Größe: Prüft, ob automatische Größenanpassung und Scrubbing für Cache-Volumes aktiviert sind, um eine optimale Größe zu gewährleisten und den Cache auf häufig genutzte Daten zu konzentrieren, um maximale Effizienz zu erzielen.
* Inaktive Blockgeräte: Es wird empfohlen, Blockgerätedaten zu archivieren oder ein Blockgerät zu löschen, wenn es sieben aufeinanderfolgende Tage lang nicht verwendet wurde.
* Logische Berichterstattung für Storage-VMs: Prüft, ob die Standardeinstellung für die Berichterstattung einer Storage-VM auf „logisch“ gesetzt ist, was eine bessere Transparenz der Speichernutzung auf Volume-Ebene ermöglicht.




==== Zusätzliche Karten für Blockgeräte

Drei neue Karten wurden auf der Registerkarte „Blockgeräte“ im Speicherworkload hinzugefügt, um einen schnellen Überblick über die Nutzung und den Schutzstatus von Blockgeräten zu bieten:

* Speichereffizienzen: Zeigt die genutzte und verfügbare Speicherkapazität an; die genutzte Kapazität wird nach SSD- und Kapazitätspool-Speicherebenen aufgeschlüsselt.
* Geschützte Geräte: Zeigt den Prozentsatz der Blockgeräte mit Snapshots, Remote-Replikation, NetApp Autonomous Ransomware Protection (ARP/AI) und Backups an.
* Inaktive Blockgeräte: Zeigt an, ob Blockgeräte sieben Tage in Folge nicht verwendet wurden, und hilft Ihnen so, ungenutzte Ressourcen effektiv zu identifizieren und zu verwalten. Von hier aus können Sie link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-storage.html#archive-the-data-of-an-inactive-block-device["Speicherplatz für ungenutzte Blockgeräte freigeben"].




==== Unterstützung bei der Erstellung und Verwaltung von Initiatorgruppen

NetApp Workload Factory unterstützt das Erstellen und Verwalten von Initiatorgruppen (igroups) für Blockspeicher in FSx for ONTAP Dateisystemen. Initiatorgruppen verbinden Blockgeräte (LUNs) mit den Rechenressourcen, die darauf zugreifen dürfen, und bieten eine Berechtigungsebene für Blockspeicher in SAN-Umgebungen.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-igroup.html["Erstellen Sie eine Initiatorgruppe in NetApp Workload Factory"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-igroups.html["Bestehende Initiatorgruppen in NetApp Workload Factory verwalten"]




=== VMware-Workloads



==== Well-architected Analyse für Amazon Elastic VMware Service

Workload Factory bietet jetzt eine automatisierte, gut strukturierte Analyse für Ihre Amazon Elastic VMware Service (EVS)-Umgebungen. Tägliche Scans identifizieren Konfigurationsabweichungen und bieten detaillierte Empfehlungen zur Behebung, damit Sie optimalen Betrieb, Sicherheit und Kosteneffizienz aufrechterhalten können.

Scans werden mithilfe von AWS-APIs durchgeführt – keine vSphere-Anmeldeinformationen oder vCenter-Konnektivität erforderlich. Die Ergebnisse sind im neuen Tab *Well-architected status* innerhalb Ihrer EVS-Umgebungsdetails verfügbar.

Diese Veröffentlichung enthält Einblicke in:

* *Status des Instanzstopp-/Beendigungsschutzes*: Identifiziert EVS-Knoten ohne EC2-Stopp- oder Beendigungsschutz. Das Stoppen oder Beenden von EVS-Knoten über die EC2-Konsole kann zur Nichtverfügbarkeit von virtuellen Maschinendaten oder zu Datenverlust führen.
* *Ausrichtung der Clusterknotenpartitionierung*: Erkennt Fehlausrichtungen der Partitionierung, die zu erheblichem Leistungsverlust oder Ausfallzeiten führen können, wenn eine Partition innerhalb einer AWS Availability Zone ausfällt. Jede Erkenntnis umfasst Schweregrad, detaillierte Ergebnisse mit Informationen zu den betroffenen Ressourcen sowie schrittweise Behebungsverfahren basierend auf AWS Best Practices.


link:view-evs-well-architected.html["Implementieren Sie gut strukturierte Konfigurationen"]



=== Einrichtung und Administration



==== Gut konzipierte Updates

NetApp Workload Factory umfasst die well-architected assessment für Elastic VMware Service (EVS) Workloads und fügt neue Konfigurationen für Storage- und Datenbank-Workloads hinzu.

* *VMware workloads* NetApp Workload Factory bietet Best Practices und Empfehlungen für den Betrieb gut strukturierter Amazon Elastic VMware Service (EVS) Workloads.
+
link:https://docs.netapp.com/us-en/workload-vmware/view-evs-well-architected.html["Implementieren Sie gut strukturierte EVS-Konfigurationen"^]

* *Speicher-Workloads* Mehrere neue Konfigurationen wurden der Funktion „Gut strukturiert“ im Bereich „Speicher-Workloads“ hinzugefügt, damit Sie mehr Einblick in Speicherleistung und -kosten erhalten.
+
** Logische Berichterstellung für Storage-VMs
** Cache-Volume-Größe optimieren
** Verwaiste Blockgeräte
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implementieren Sie gut strukturierte Dateisystemkonfigurationen für Storage-Workloads"^]



* *Datenbank-Workloads* Workload Factory für Datenbanken beinhaltet neue Speicherkonfiguration für Oracle zur Aktivierung und Einrichtung von Direct NFS (dNFS), um die I/O-Leistung zu verbessern und die Last auf dem Host und dem Speichersystem zu verringern.
+
** dNFS-Aktivierung
** dNFS konsistente IP-Auflösung
** dNFS Konfigurationsdatei
** dNFS `nosharecache`
+
link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementieren Sie gut strukturierte Datenbank-Workloads"^]







==== Neue Berechtigungen für Storage

Neue Berechtigungen wurden zur Storage-Workload hinzugefügt, um Verbesserungen bei der Verwaltung von S3-Zugriffspunkten zu ermöglichen.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Änderungsprotokoll der Berechtigungsreferenz"]



=== EDA-Workloads



==== Erweiterte Dashboard-Filterung mit anpassbaren Tags

Sie können nun bis zu fünf benutzerdefinierte Filter im EDA-Dashboard basierend auf Ihren AWS-Tags konfigurieren. Jeder benutzerdefinierte Filter enthält einen Labelnamen, einen AWS-Tag-Schlüssel und einen Auswahltyp (Einzel- oder Mehrfachauswahl).

Die Mehrfachauswahl ermöglicht es Ihnen, mehrere Werte gleichzeitig auszuwählen, während die Einzelauswahl Sie auf einen Wert zur gleichen Zeit beschränkt. Benutzerdefinierte Filter erscheinen in der Reihenfolge, in der Sie sie konfigurieren, was es einfach macht, Ihre am häufigsten verwendeten Filter zu organisieren.

Wenn Sie keine benutzerdefinierten Filter konfigurieren, bleiben die Standardfilter (Dateisystem, Volume-Typ und Zeitbereich) verfügbar, sodass Sie Ihre Dashboards weiterhin anzeigen und interaktiv nutzen können.

https://docs.netapp.com/us-en/workload-eda/task-configure-dashboard.html["Erfahren Sie mehr über die Konfiguration benutzerdefinierter Filter"^].



==== Volumendetailansicht für granulare Leistungsanalyse

Das Dashboard bietet nun zwei Ansichtsmodi: Gesamtansicht und Volumenansicht. Die Gesamtansicht zeigt aggregierte Kennzahlen über alle Volumina hinweg, während die Volumenansicht die individuelle Performance der Top 10 Volumina im Zeitverlauf anzeigt.

In der Volumenansicht bieten interaktive Tooltips beim Überfahren mit der Maus detaillierte Informationen zu jedem Volumen, einschließlich Volumenname, Metriken und zeitbezogener Werte. Wenn dieselben Volumen in mehreren Komponenten erscheinen, erleichtert eine konsistente Farbcodierung das Nachverfolgen bestimmter Volumen über verschiedene Metriken hinweg.

https://docs.netapp.com/us-en/workload-eda/task-configure-dashboard.html#view-volume-details["Erfahren Sie mehr über die Anzeige von Volume-Details"^].



==== Latenzanalyse für proaktive Leistungsüberwachung

Die Latenzanalyse ermöglicht es Ihnen, die Lese- und Schreiblatenz Ihrer FSx for ONTAP-Dateisysteme zu überwachen. Sie können anpassbare Warn- und kritische Ereignisschwellenwerte konfigurieren, um Leistungsengpässe proaktiv zu identifizieren, bevor sie Ihre EDA-Workloads beeinträchtigen.

Die Tabelle der Latenzereignisse zeigt alle Warn- und kritischen Ereignisse an, sodass Sie die Volume-Leistung überwachen und Volumes identifizieren können, die eine Optimierung erfordern.

Diese Funktion erfordert AWS-Zugangsdaten und ist über das Menü Latenz im EDA-Dashboard zugänglich.

https://docs.netapp.com/us-en/workload-eda/task-monitor-latency.html["Erfahren Sie mehr über Latenzanalyse"^].
