---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: Informieren Sie sich über die neuesten Änderungen an den Workloads, die Teil der BlueXP -Workload-Fabrik sind. 
---
= Kürzliche Änderungen in der BlueXP  Workload-Farm
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Informieren Sie sich über die neuesten Änderungen an den Workloads, die Teil der BlueXP -Workload-Fabrik sind.



== 1 2025-05-04



=== Amazon FSX für NetApp ONTAP



==== Autonomer Ransomware-Schutz für FSX für ONTAP-Filesysteme

Schützen Sie Ihre Daten mit ARP (Autonomous Ransomware Protection), einer Funktion, die Workload-Analysen in NAS-Umgebungen (NFS/SMB) nutzt, um abnormale Aktivitäten, die ein Ransomware-Angriff sein könnten, zu erkennen und zu warnen. Wird ein Angriff vermutet, erstellt ARP auch neue, unveränderliche Snapshots, anhand derer Sie Ihre Daten wiederherstellen können.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Schützen Sie Ihre Daten mit autonomem Ransomware-Schutz"]



==== Verbesserung des FlexGroup Volume-Ausgleiches

Bei einer BlueXP  Workload-Fabrik wird der FlexGroup Volume Ausgleichs-Assistent mit mehreren Layout-Optionen zur Ausbalancierung der Daten in einem FlexGroup Volume eingeführt. Die Ausbalancierung verteilt Daten gleichmäßig auf die FlexGroup-Mitglieds-Volumes.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["Bringen Sie die Kapazität in einem FlexGroup Volume wieder ins Gleichgewicht"]



==== Implementierung von Best Practices für ein FSX für ONTAP-Filesystem

Die BlueXP  Workload Factory bietet ein Dashboard, über das Sie den gut konzipierten Status Ihrer Filesystem-Konfigurationen überprüfen können. Mithilfe dieser Analyse können Sie Best Practices für Ihre FSX for ONTAP-Dateisysteme implementieren. Die Dateisystemkonfigurationsanalyse umfasst die folgenden Konfigurationen: SSD-Kapazitätsgrenze, geplante lokale Snapshots, geplante FSX für ONTAP-Backups, Daten-Tiering und Remote-Datenreplizierung.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["Informieren Sie sich über die gut konzipierte Analyse für Filesystem-Konfigurationen"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implementieren Sie Best Practices für Ihre Dateisysteme"]




==== Dual-Protokoll-Volume-Sicherheitsoptionen

Sie können entweder NTFS oder UNIX als Sicherheitstil für ein Volume auswählen, um die Methode zu bestimmen, mit der Benutzer und Berechtigungen auf ein Volume zugreifen.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Erstellen eines Volumes"]



==== Verbesserungen bei der Replizierung



===== Unterstützung für umgekehrte Replizierung von FSX für ONTAP nach On-Premises

Die umgekehrte Replizierung ist jetzt von einem FSX für ONTAP-Filesystem zu einem lokalen ONTAP-Cluster in der Workload-Factory-Konsole verfügbar.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/reverse-replication.html["Umgekehrte Replikation"]



===== Datensicherung Volume-Replizierung

Sie können jetzt Datensicherungs-Volumes replizieren.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/cascade-replication.html["Replizierung eines Datensicherheitsvolumes"]



===== Auswahl mehrerer Volumes

Es stehen mehrere Volumeauswahl zur Verfügung, sodass Sie genau die Volumes auswählen können, die Sie replizieren möchten.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Erstellen einer Replikationsbeziehung"]



===== Etiketten für Richtlinien zur langfristigen Aufbewahrung

Wenn Sie die langfristige Aufbewahrung für eine Replikationsbeziehung aktivieren, müssen die Label von Quell- und Ziel-Volumes exakt übereinstimmen. Jetzt kann BlueXP  Workload Factory automatisch fehlende Quell-Volume-Labels für Sie erstellen.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Erstellen einer Replikationsbeziehung"]



==== Der Dateiname FSX for ONTAP ist bei der Volume-Erstellung sichtbar

Wir haben die Sichtbarkeit von FSX für ONTAP-Dateisysteme während der Volume-Erstellung verbessert. Wenn Sie ein Volume erstellen, sehen Sie das FSX für ONTAP-Dateisystem, sodass Sie genau wissen, wo das Volume erstellt wird.



==== AWS-Konto ist für den Storage-Workload sichtbar

Wir haben die Account-Transparenz für den Storage Workload verbessert. Das AWS-Konto wird angezeigt, wenn Sie zu den Registerkarten *Volumes*, *Storage VMs* und *Replication* navigieren.



==== Verbesserungen bei der Verknüpfung

* Sie können einen Link aus einem FSX für ONTAP-Dateisystem in der Registerkarte Inventar schnell verknüpfen.
* BlueXP  Workload Factory unterstützt jetzt die Verwendung alternativer ONTAP-Benutzeranmeldeinformationen für die Link-Zuordnung.




==== Unterstützung der Link-Authentifizierung für AWS Secrets Manager

Sie haben jetzt die Möglichkeit, Secrets von AWS Secrets Manager zum Authentifizieren von Links zu verwenden, sodass Sie keine in der BlueXP  Workload Factory gespeicherten Anmeldeinformationen verwenden müssen.



==== Unterstützung von Tracker-Antworten

Tracker bietet jetzt API-Antworten, sodass Sie die REST API-Ausgabe zu der Aufgabe sehen können.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Überwachen Sie den Betrieb mit Tracker"]



==== Kapazitätsvalidierung beim Wiederherstellen eines Volumes aus einem Backup

Beim Wiederherstellen eines Volumes aus einem Backup ermittelt die BlueXP  Workload Factory, ob Sie über genügend Kapazität für die Wiederherstellung verfügen. Andernfalls kann automatisch SSD-Storage-Tier-Kapazität hinzugefügt werden.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/restore-from-backup.html["Stellen Sie ein Volume aus einem Backup wieder her"]



==== Unterstützung alternativer ONTAP-Benutzeranmeldeinformationen

Workload Factory unterstützt jetzt alternative Sätze von ONTAP-Anmeldeinformationen zur Erstellung von Dateisystemen, um Sicherheitsrisiken zu minimieren. Anstatt nur den Benutzer fsxadmin zu verwenden, können Sie einen anderen Satz von ONTAP-Anmeldeinformationen auswählen oder wählen, kein Passwort für Benutzer von fsxadmin und vsaadmin anzugeben.



==== Terminologie für Berechtigungen wurde aktualisiert

Die Benutzeroberfläche und Dokumentation der Workload Factory verwenden jetzt „Read-Only“, um auf Leseberechtigungen und „Read-Write“ zu verweisen, um Berechtigungen zu automatisieren.



=== Datenbank-Workloads



==== Dashboard-Verbesserungen

* Kunden- und regionsübergreifende Ansichten sind verfügbar, wenn Sie in der BlueXP  Workload Factory-Konsole zwischen den Registerkarten navigieren. Die neuen Ansichten verbessern das Ressourcenmanagement, die Überwachung und die Optimierung.
* Über die Kachel *potenzielle Einsparungen* im Dashboard können Sie schnell überprüfen, was Sie sparen könnten, indem Sie vom Amazon Elastic Block Store oder Amazon FSX for Windows File Server zu FSX for ONTAP wechseln.




==== Ad-hoc-Scans für Datenbankkonfigurationen verfügbar

Die BlueXP -Workload-Fabrik für Datenbanken scannt gemanagte Microsoft SQL Server-Instanzen automatisch mit FSX für ONTAP Storage auf potenzielle Konfigurationsprobleme. Zusätzlich zum täglichen Scan können Sie jetzt jederzeit scannen.



==== Entfernung von Beurteilungsunterlagen vor Ort

Nachdem Sie die Einsparungen für einen lokalen Microsoft SQL Server-Host untersucht haben, haben Sie die Möglichkeit, den lokalen Host-Datensatz aus der BlueXP  Workload Factory zu entfernen.



==== Optimierungsverbesserungen



===== Klonbereinigung

Die Bewertung und Korrektur der Klonbereinigung identifiziert und managt alte und teure Klone. Klone, die älter als 60 Tage sind, können aktualisiert oder aus der BlueXP -Workload-Werkseinstellungen gelöscht werden.



===== Verschieben und Verwerfen der Konfigurationsanalyse

Einige Konfigurationen gelten möglicherweise nicht für Ihre Datenbankumgebungen. Sie haben jetzt die Möglichkeit, eine bestimmte Konfigurationsanalyse um 30 Tage zu verschieben oder die Analyse zu verwerfen.



==== Entfernung von Beurteilungsunterlagen vor Ort

Nachdem Sie die Einsparungen für einen lokalen Microsoft SQL Server-Host untersucht haben, haben Sie die Möglichkeit, den lokalen Host-Datensatz aus der BlueXP  Workload Factory zu entfernen.



==== Terminologie für Berechtigungen wurde aktualisiert

Die Benutzeroberfläche und Dokumentation der Workload Factory verwenden jetzt „Read-Only“, um auf Leseberechtigungen und „Read-Write“ zu verweisen, um Berechtigungen zu automatisieren.



=== VMware-Workloads



==== Verbesserungen bei Amazon EC2 Migration Advisor

Diese Version der BlueXP  Workload-Farm für VMware umfasst folgende Verbesserungen zur Nutzung des Amazon EC2 Migrationsberaters:

*Einblicke in die NetApp-Dateninfrastruktur als Datenquelle*: Workload Factory stellt jetzt eine direkte Verbindung mit NetApp Data Infrastructure Insights her, um VMware Implementierungsinformationen zu erfassen, wenn Sie den Data Collector des EC2 Migration Advisor verwenden.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Erstellen eines Implementierungsplans für Amazon EC2 mithilfe des Migrationsberaters"]



==== Terminologie für Berechtigungen wurde aktualisiert

Die Benutzeroberfläche und Dokumentation der Workload Factory verwenden jetzt „Read-Only“, um auf Leseberechtigungen und „Read-Write“ zu verweisen, um Berechtigungen zu automatisieren.



=== GenAI-Workloads



==== Unterstützung von NetApp ONTAP Connector für Amazon Q

Diese Version von GenAI bietet Unterstützung für NetApp ONTAP Connector für Amazon Q, damit Sie Connectors für Amazon Q Business erstellen können. Nutzen Sie den Amazon Q Business KI-Assistenten schnell und einfach mit einer geringeren Erstkonfiguration als mit dem Aufbau einer GenAI Knowledge Base für Amazon Bedrock.

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["Erstellen Sie einen GenAI-Connector für Amazon Q Business"]



==== Verbesserter Support für Chatmodelle

GenAI unterstützt jetzt die folgenden zusätzlichen Chatmodelle für Wissensdatenbanken:

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Mistral KI-Modelle"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Amazon Titan Textmodelle"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Meta Llama Modelle"^]
* link:https://docs.ai21.com/["Jamba 1.5 Modelle"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Co-here Command-Modelle"^]
* link:https://aws.amazon.com/bedrock/deepseek/["Deepseek-Modelle"^]


GenAI unterstützt die Modelle von jedem Provider, die von Amazon Bedrock unterstützt werden: link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Unterstützte Basismodelle in Amazon Bedrock"^]

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html["Einrichtung einer GenAI Knowledge Base"]



==== Terminologie für Berechtigungen wurde aktualisiert

Die Benutzeroberfläche und Dokumentation der Workload Factory verwenden jetzt „Read-Only“, um auf Leseberechtigungen und „Read-Write“ zu verweisen, um Berechtigungen zu automatisieren.



=== Einrichtung und Administration



==== Autocomplete-Unterstützung für CloudShell

Wenn Sie BlueXP  Workload Factory CloudShell verwenden, können Sie einen Befehl eingeben und die Tabulatortaste drücken, um die verfügbaren Optionen anzuzeigen. Wenn mehrere Möglichkeiten vorhanden sind, zeigt die CLI eine Liste mit Vorschlägen an. Diese Funktion steigert die Produktivität, indem Fehler minimiert und die Befehlsausführung beschleunigt wird.



==== Terminologie für Berechtigungen wurde aktualisiert

Die Benutzeroberfläche und Dokumentation der Workload Factory verwenden jetzt „Read-Only“, um auf Leseberechtigungen und „Read-Write“ zu verweisen, um Berechtigungen zu automatisieren.



== 1 2025-04-04



=== Datenbank-Workloads



==== Optimierungsverbesserungen

Bei der Optimierung Ihrer Datenbankumgebungen stehen neue Optimierungsbewertungen, Korrekturmaßnahmen und die Anzeige mehrerer Ressourcen zur Verfügung.



===== Stabilitätsbewertungen

Die Verbesserungen umfassen neue Stabilitätsbewertungen, um zu überprüfen, ob Datenredundanz- und Disaster-Recovery-Funktionen für Ihre Datenbankumgebungen konfiguriert werden.

* FSX für ONTAP-Backups: Analysiert, ob FSX für ONTAP-Dateisysteme, die die Volumes der SQL Server-Instanz bedienen, mit geplanten FSX für ONTAP-Backups konfiguriert sind.
* Regionsübergreifende Replizierung: Bewertet, ob FSX für ONTAP-Dateisysteme, die Microsoft SQL Server-Instanzen bedienen, mit regionsübergreifender Replizierung konfiguriert sind.




===== Problembehebung

Receive Side Scaling (RSS) Remediation konfiguriert RSS, um die Netzwerkverarbeitung auf mehrere Prozessoren zu verteilen und eine effiziente Lastverteilung zu gewährleisten.



===== Korrektur lokaler Snapshots

Lokale Snapshot-Korrektur richtet Snapshot-Richtlinien für Volumes für Ihre Microsoft SQL Server-Instanzen ein, um Ihre Datenbankumgebungen bei Datenverlust ausfallsicher zu halten.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimieren von Konfigurationen"]



===== Unterstützung für die Auswahl mehrerer Ressourcen

Bei der Optimierung von Datenbankkonfigurationen können Sie nun spezifische Ressourcen anstelle aller Ressourcen auswählen.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimieren von Konfigurationen"]



==== Verbesserte Bestandansicht

Die Registerkarte „Inventar“ in der Arbeitslastwerkkonsole wurde so optimiert, dass sie nur SQL-Server enthält, die auf Amazon FSX für NetApp ONTAP ausgeführt werden. Auf der Registerkarte „Einsparungen“ finden Sie jetzt SQL-Server vor Ort, die auf Amazon Elastic Block Store und Amazon FSX für Windows File Server ausgeführt werden.



==== Schnelles Erstellen für PostgreSQL-Serverimplementierung verfügbar

Sie können diese schnelle Bereitstellungsoption verwenden, um einen PostgreSQL-Server mit HA-Konfiguration und integrierten Best Practices zu erstellen.

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["Erstellen Sie einen PostgreSQL-Server in der BlueXP  Workload Factory"]



== 1 2025-03-30



=== Amazon FSX für NetApp ONTAP



==== Automatisches Kapazitätsmanagement für Scale-out-Systeme

Workload Factory sucht nun nach verfügbaren Inodes in Volumes und erhöht ihre Anzahl entsprechend den konfigurierten Schwellenwerten für das automatische Kapazitätsmanagement. Diese Funktion unterstützt automatisches Kapazitätsmanagement für Scale-out-Systeme. Sie können das Inodes-Management im Rahmen des automatischen Kapazitätsmanagements aktivieren.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["Aktivieren Sie das automatische Kapazitätsmanagement"]



==== FlexGroup-AusgleichAPI

An der BlueXP  Workload-Fabrik wird die FlexGroup-Ausgleichs-API veröffentlicht, über die Sie einen Plan zum Lastausgleich der Daten in einer FlexGroup ausführen können. Durch die Ausbalancierung werden Daten gleichmäßig auf die Mitglieds-Volumes verteilt.

link:https://console.workloads.netapp.com/api-doc["BlueXP  Workload-API-Dokumentation"]



==== Datenform zur Replizierung umfasst Anwendungsfälle

Das Formular Daten replizieren enthält jetzt Anwendungsfälle, um das Ausfüllen des Formulars zu erleichtern. Wählen Sie einen der folgenden Anwendungsfälle für die Datenreplizierung aus: Migration, Disaster Recovery für häufig benötigte Daten, Cold-Disaster-Recovery, Archivierung oder andere. Nachdem Sie einen Anwendungsfall ausgewählt haben, empfiehlt Workload Factory Werte im Einklang mit Best Practices. Sie können die vorausgewählten Werte akzeptieren oder die Werte im Formular anpassen.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Datenreplizierung"]



==== Änderungen der Terminologie bei der Data Tiering-Richtlinie

Wenn Sie sich nun für eine Tiering-Richtlinie während der Volume-Erstellung, Datenreplizierung oder Aktualisierung vorhandener Tiering-Richtlinien entscheiden, finden Sie neue Begriffe zur Beschreibung der Tiering-Richtlinien.

* _Ausgeglichen (Auto)_
* _Kostenoptimiert (Alle)_
* _Performance Optimized (nur Snapshots)_




==== Details der Sicherheitsgruppe für die Dateisystemerstellung

Im Rahmen des Dateisystemerstellungsprozesses FSX für ONTAP wird eine Sicherheitsgruppe erstellt. Details zu Sicherheitsgruppen wie Protokolle, Ports und Rollen sind jetzt verfügbar.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Erstellen Sie ein Dateisystem"]



=== VMware-Workloads



==== Verbesserungen bei Amazon EC2 Migration Advisor

Diese Version der BlueXP  Workload-Farm für VMware bietet mehrere Verbesserungen bei der Erfahrung des Amazon EC2 Migration Advisor:

* *Verbesserte Anleitung zur Volume-Zuweisung*: Die Informationen zur Volume-Zuweisung im EC2-Migrationsberater „Classify“ und „Package“ bietet eine verbesserte Lesbarkeit und Benutzerfreundlichkeit. Es werden nützlichste Informationen zu jedem Volume angezeigt, sodass Sie Volumes besser identifizieren und festlegen können, wie sie zugewiesen werden.
* *Data Collector-Skript-Effizienzverbesserungen*: Das Data Collector-Skript des EC2-Migrationsberaters optimiert die CPU-Nutzung bei der Erfassung von Daten für kleinere VM-Bereitstellungen.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Erstellen eines Implementierungsplans für Amazon EC2 mithilfe des Migrationsberaters"]



=== GenAI-Workloads



==== Verbesserte Unterstützung von Dateitypen

Diese Version von GenAI führt die Unterstützung von JSON- und JSONP-Dateiformaten ein, wenn Dateien aus Datenquellen erstellt `.json` werden. JSON-Dateien mit geschachtelten Objekten werden unterstützt, wobei die Unterstützung für verschachtelte Arrays eingeschränkt ist.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/identify-data-sources-knowledge-base.html#supported-data-source-file-formats["Unterstützte Datenquelldateiformate"]



==== Internationalisierungsunterstützung für die externe Chatbot-Beispielanwendung

Sie können die Benutzeroberfläche der externen GenAI-Beispielanwendung für Chatbot jetzt ganz einfach in eine andere Sprache oder ein anderes Gebietsschema ändern.

link:https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/AI/GenAI-ChatBot-application-sample#netapp-workload-factory-genai-sample-application["Externe Beispiel-Chatbot-Anwendung von GenAI"]



==== Unterstützung für das Anthropic Claude Sonnet 3.7 Chat-Modell

GenAI bietet jetzt Unterstützung für das Anthropic Claude 3.7 Sonnet Chat-Modell. Die Beta-Funktionen von Claude 3.7 Sonnet ermöglichen bis zu 128K Output-Token pro Anfrage und unterstützen neue Computer-Use-Aktionen. Claude 3.7 Sonnet Extended Thinking Mode wird in einer zukünftigen GenAI Version unterstützt.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Einrichtung einer GenAI Knowledge Base"]



==== Unterstützung für das Hinzufügen von Datenquellen von generischen NFS/SMB-Freigaben

Mit der Workload-Factory-API können Sie jetzt eine Datenquelle aus einer generischen NFSv3, NFSv4 oder SMB-Freigabe hinzufügen. Wenn Sie eine Datenquelle aus einer NFS- oder SMB-Freigabe hinzufügen, bleibt das Knowledge-Base-Volume auf einem Amazon FSX for NetApp ONTAP-Volume erhalten. Die Workload Factory Web UI unterstützt diese Funktion in einer zukünftigen Version.

link:https://console.workloads.netapp.com/api-doc["Verwenden Sie die Workload Factory API"^]



==== VPC-Peering-Unterstützung

Jetzt können Sie die GenAI-Infrastruktur über dieselbe Region hinweg implementieren link:https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html["Peered Virtual Private Clouds (VPCs)"^]und dasselbe AWS-Konto verwenden. Sie können die AI-Engine in einer VPC implementieren und dann eine Knowledge Base in einer Peering-VPC erstellen. Anschließend können Sie Amazon FSX für NetApp ONTAP-Dateisysteme in einem Peering-VPC auswählen.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Einrichtung einer GenAI Knowledge Base"]



=== Einrichtung und Administration



==== CloudShell meldet AI-generierte Fehlermeldungen für ONTAP-CLI-Befehle

Bei der Verwendung von CloudShell können Sie jedes Mal, wenn Sie einen ONTAP-CLI-Befehl ausgeben und ein Fehler auftritt, AI-generierte Fehlermeldungen erhalten, die eine Beschreibung des Fehlers, die Ursache des Fehlers und eine detaillierte Lösung enthalten.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Verwenden Sie CloudShell"]



==== iam:SimulatePermissionPolicy-Berechtigungsaktualisierung

Sie können jetzt die Berechtigung über die Konsole für die Werkseinstellungen managen `iam:SimulatePrincipalPolicy`, wenn Sie zusätzliche AWS-Kontoinformationen hinzufügen oder eine neue Workload-Funktion hinzufügen, z. B. den GenAI-Workload.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Änderungsprotokoll für Berechtigungen"]



== 1 2025-03-03



=== Datenbank-Workloads



==== PostgreSQL-Hochverfügbarkeitskonfiguration

Sie können jetzt eine HA-Konfiguration für PostgreSQL Server implementieren.

link:https://review.docs.netapp.com/us-en/workload-databases_explore-savings-updates/create-postgresql-server.html["Erstellen Sie einen PostgreSQL-Server"]



==== Terraform-Unterstützung für die PostgreSQL-Servererstellung

Sie können jetzt Terraform aus der Codebox verwenden, um PostgreSQL zu implementieren.

* link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["Erstellen Sie einen PostgreSQL-Datenbankserver"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Verwenden Sie Terraform aus der Codebox"]




==== Stabilitätsbewertung für lokalen Snapshot-Zeitplan

Für Datenbank-Workloads steht eine neue Bewertung der Ausfallsicherheit zur Verfügung. Wir bewerten, ob Volumes für Ihre Microsoft SQL Server Instanzen gültige geplante Snapshot-Richtlinien aufweisen. Snapshots sind zeitpunktgenaue Kopien Ihrer Daten und sorgen dafür, dass Ihre Datenbankumgebungen auch bei Datenverlusten ausfallsicher bleiben.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimieren von Konfigurationen"]



==== MAXDOP-Korrektur für Datenbank-Workloads

Die BlueXP -Workload-Fabrik für Datenbanken unterstützt jetzt die Wiederherstellung der maximalen Parallelität (Maximum Degree of Parallelism, MAXDOP)-Serverkonfiguration. Wenn die MAXDOP-Konfiguration nicht optimal ist, können Sie die Konfiguration für die BlueXP -Workload Factory optimieren lassen.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimieren von Konfigurationen"]



==== Bericht zur Einsparungsanalyse per E-Mail

Wenn Sie die Einsparungen für Ihre Amazon Elastic Block Store und FSX für Windows File Server Storage-Umgebungen im Vergleich zu FSX für ONTAP erkunden, können Sie sich nun den Empfehlungsbericht per E-Mail an sich selbst, Teammitglieder und Kunden senden.



== 1 2025-03-02



=== Amazon FSX für NetApp ONTAP



==== Automatische Verbesserungen beim Kapazitätsmanagement

Bei Aktivierung des automatischen Kapazitätsmanagements prüft die BlueXP  Workload Factory nun, ob ein Filesystem seinen Kapazitätsschwellenwert alle 30 Minuten anstatt alle 2 Stunden erreicht hat.

Die Einstellung für bereitgestellte IOPS wird nicht mehr beeinflusst, wenn der Kapazitätsschwellenwert erreicht wird.



==== Unveränderliche Snapshots

Sie können Snapshots nun über einen bestimmten Aufbewahrungszeitraum sperren und sie damit unveränderbar machen. Das Sperren verhindert unbefugten Zugriff und böswillige Löschung von Snapshots. Sie können unveränderliche Snapshots während der Erstellung der Snapshot-Richtlinie, beim Erstellen manueller Snapshots und nach der Snapshot-Erstellung aktivieren.



==== Aktualisierung unveränderlicher Dateien

Nun können Sie an Ihrer Konfiguration unveränderlicher Dateien folgende Änderungen vornehmen: Aufbewahrungsrichtlinie, Aufbewahrungszeitraum, Autofestzeitraum und Modus für anhängen von Volumes.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-immutable-files.html["Management unveränderlicher Dateien"]



==== Verbesserungen bei der Datenreplizierung

* Cross-Account-Replizierung: Die Replizierung zwischen zwei AWS-Konten wird in der BlueXP  Workload Factory-Konsole sowie in der Replikationsverwaltung unterstützt.
* Replikation anhalten und fortsetzen: Sie können geplante Replikations-Updates vom Quell-Volume zum Ziel-Volume unterbrechen (stilllegen) und dann den Replikationszeitplan wieder aufnehmen, sobald Sie bereit sind. Während der Pause werden Quell- und Ziel-Volumes unabhängig und das Ziel-Volume wird von schreibgeschützten auf Schreib- und Lesezugriff umgestellt.
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/pause-resume-replication.html["Anhalten und Wiederaufnehmen einer Replikationsbeziehung"]





==== CloudShell-Events in Tracker

Jetzt können Sie CloudShell-Ereignisse in Tracker verfolgen.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Überwachen und verfolgen Sie den Betrieb mit Tracker"]



=== VMware-Workloads



==== Verbesserungen bei Amazon EC2 Migration Advisor

Diese Version der BlueXP  Workload-Farm für VMware bietet mehrere Verbesserungen bei der Erfahrung des Amazon EC2 Migration Advisor:

* *Geschätzter Instanztyp*: Der Migrationsberater kann nun die Anforderungen Ihrer Umgebung prüfen und für jede VM einen geschätzten Amazon EC2 Instanztyp angeben. Sie können auswählen, den geschätzten Instanztyp für jede VM im Schritt „Umfang“ des Migrationsberaters einzubeziehen.
* *Möglichkeit Amazon EBS Volumes zu empfehlen*: Der Migrationsberater kann aufgrund bestimmter Kapazitäts- oder Performance-Anforderungen einer bestimmten Region nun die Migration von Daten-Volumes in den Amazon Elastic Block Store (EBS) anstelle von Amazon FSX for NetApp ONTAP empfehlen.
* * Verbesserte automatische Dateisystemzuweisung*: Amazon FSX für NetApp ONTAP Dateisystemzuweisung wurde verbessert, um Kosten besser zu optimieren und Durchsatz zu minimieren.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Erstellen eines Implementierungsplans für Amazon EC2 mithilfe des Migrationsberaters"]



=== GenAI-Workloads



==== Verbesserungen des integrierten Chatbot

Sie können jetzt Fragen und Antworten direkt in die Zwischenablage kopieren, die Größe des Chat-Fensters anpassen und dessen Titel ändern. Darüber hinaus können Chat-Antworten jetzt Tabellen enthalten, die auch kopierbar sind.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/test-knowledgebase.html["Testen Sie eine GenAI Knowledge Base"]



==== Unterstützung bei der Chat-Antwort

Die Chat-Antworten enthalten nun Zitate, in denen die Dateien und Datenpakete aufgelistet sind, die zur Generierung der Antwort verwendet wurden.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/test-knowledgebase.html["Testen Sie eine GenAI Knowledge Base"]



==== Verbesserte Unterstützung von Dateitypen

Diese Version von GenAI bietet erweiterte Dateiunterstützung:

* Chat-Modelle bieten eine verbesserte CSV-Unterstützung. Dies ermöglicht nützlichste Antworten beim Abfragen von Daten aus CSV-Dateien.
* GenAI kann jetzt Apache Parkett Dateien aus Datenquellen aufnehmen.
* GenAI unterstützt jetzt die Aufnahme von Microsoft Word DOCX-Dateien, die Bilder enthalten. In DOCX-Dokumenten eingebettete Bilder werden gescannt, und Texteinblicke aus den eingebetteten Bildern werden in Antworten auf Knowledge-Base-Abfragen berücksichtigt.


link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/identify-data-sources-knowledge-base.html#supported-data-source-file-formats["Unterstützte Datenquelldateiformate"]



== 1 2025-02-02



=== Einrichtung und Administration



==== CloudShell ist in der BlueXP -Workload-Factory-Konsole verfügbar

CloudShell ist an jedem beliebigen Ort in der BlueXP -Workload-Factory-Konsole verfügbar. CloudShell ermöglicht Ihnen, die in Ihrem BlueXP -Konto angegebenen AWS- und ONTAP-Anmeldeinformationen zu verwenden und AWS CLI-Befehle oder ONTAP CLI-Befehle in einer Shell-ähnlichen Umgebung auszuführen.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Verwenden Sie CloudShell"]



==== Berechtigungsaktualisierung für Datenbanken

Die folgende Berechtigung ist jetzt im _read_ Modus für Datenbanken verfügbar: `iam:SimulatePrincipalPolicy`.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Änderungsprotokoll für Berechtigungen"]
