= Verbesserungen des Einsparungsrechners
:allow-uri-read: 




=== Verbesserungen des Einsparungsrechners

* Beschreibungen der Kostenvoranschlafe
+
Sie erfahren nun, wie die geschätzten Kosten mithilfe des Einsparungsrechners berechnet werden. Sie können mithilfe von Amazon Elastic Block Store Storage eine Beschreibung aller Berechnungen für Ihre Microsoft SQL Server Instanzen im Vergleich zur Nutzung von Amazon FSX für ONTAP Storage einsehen.

* Unterstützung der Always-On-Verfügbarkeitsgruppe
+
Datenbanken ermöglichen jetzt mit Microsoft SQL Server unter Verwendung von Amazon Elastic Block Store Kostenersparnisse für die Bereitstellung von Always-on-Verfügbarkeitsgruppen.

* Optimierung der SQL Server-Lizenzierung mit FSX für ONTAP
+
Der Datenbank-Rechner bestimmt, ob die mit Amazon Elastic Block Store verwendete SQL Lizenzversion für Ihre Datenbank-Workloads optimiert ist. Sie erhalten eine Empfehlung für die optimale SQL-Lizenz mit FSX für ONTAP Storage.

* Mehrere SQL Server Instanzen
+
Datenbanken ermöglichen jetzt Kosteneinsparungen bei einer Konfiguration, die mehrere Microsoft SQL Server Instanzen mithilfe von Amazon Elastic Block Store hostet.

* Anpassen der Berechnungseinstellungen
+
Sie können jetzt die Einstellungen für Microsoft SQL Server, Amazon EC2 und Elastic Block Store anpassen und die Einsparungen manuell berechnen. Mit dem Einsparungsrechner wird die beste Konfiguration basierend auf den Kosten ermittelt.



link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html["Informieren Sie sich über Kosteneinsparungen mit FSX für ONTAP für Ihre Datenbank-Workloads^."]
