= Optimieren Sie Ihre Microsoft SQL Server Workloads kontinuierlich mithilfe von Datenbanken
:allow-uri-read: 




=== Optimieren Sie Ihre Microsoft SQL Server Workloads kontinuierlich mithilfe von Datenbanken

Die BlueXP  Workload-Farm ermöglicht fortlaufende Optimierung und Einhaltung von Best Practices für die Storage-Komponenten Ihrer Microsoft SQL Server-Workloads in Amazon FSX für NetApp ONTAP. Diese Funktion scannt Ihren Microsoft SQL Server-Bestand offline und bietet Ihnen einen umfassenden Bericht mit Einblicken, Möglichkeiten und Empfehlungen, mit denen Sie optimale Performance, Kosteneffizienz und Compliance erzielen.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["SQL Server-Workloads optimieren"]



=== Terraform-Unterstützung

Sie können jetzt Terraform aus der Codebox verwenden, um Microsoft SQL Server bereitzustellen.

* link:https://docs.netapp.com/us-en/workload-databases/create-database-server.html["Erstellen Sie einen Datenbankserver"^]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Verwenden Sie Terraform aus der Codebox"^]

