= Kontinuierliche Optimierung ergänzt die Behebung und Bewertung von Compute-Ressourcen
:allow-uri-read: 




=== Kontinuierliche Optimierung ergänzt die Behebung und Bewertung von Compute-Ressourcen

Datenbanken bieten jetzt Einblicke und Empfehlungen, um Compute-Ressourcen für Microsoft SQL Server Instanzen zu optimieren. Wir messen die CPU-Auslastung und nutzen den AWS Compute Optimizer Service, um Instanztypen der optimalen Größe zu empfehlen und Sie über verfügbare Betriebssystem-Patches zu informieren. Wenn Sie Compute-Ressourcen optimieren, können Sie fundierte Entscheidungen zu Instanztypen treffen, was zu Kosteneinsparungen und einer effizienten Ressourcenauslastung führt.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimierte Konfigurationen von Compute-Ressourcen"]



=== PostgreSQL-Unterstützung

Sie können jetzt eigenständige PostgreSQL-Server-Implementierungen in Datenbanken implementieren und verwalten.

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["Erstellen Sie einen PostgreSQL-Server"]
