= Benutzerdefinierter Snapshot-Name
:allow-uri-read: 




=== Benutzerdefinierter Snapshot-Name

Sie können jetzt einen Snapshot-Namen für einen Ad-hoc-Snapshot bereitstellen.

link:https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#protect-a-knowledge-base-with-snapshots["Schützen Sie eine Wissensdatenbank mit Snapshots"]



=== Individueller Name für die AI Engine Instance

Sie können der KI-Engine-Instanz jetzt während der Implementierung einen benutzerdefinierten Namen geben.

link:https://docs.netapp.com/us-en/workload-genai/deploy-infrastructure.html["Implementierung der GenAI-Infrastruktur"]



=== Wiederherstellung beschädigter oder fehlender GenAI-Infrastruktur

Wenn Ihre KI-Engine beschädigt wird oder irgendwie gelöscht wird, können Sie sie auf der Workload-Farm für Sie neu erstellen lassen. Die Workload Factory verbindet Ihre Wissensdatenbanken nach Abschluss der Neuerstellung automatisch mit der Infrastruktur, sodass sie einsatzbereit sind.

link:https://docs.netapp.com/us-en/workload-genai/troubleshooting.html["Fehlerbehebung"]
