= Autonomer Ransomware-Schutz für FSX für ONTAP-Filesysteme
:allow-uri-read: 




=== Autonomer Ransomware-Schutz für FSX für ONTAP-Filesysteme

Schützen Sie Ihre Daten mit ARP (Autonomous Ransomware Protection), einer Funktion, die Workload-Analysen in NAS-Umgebungen (NFS/SMB) nutzt, um abnormale Aktivitäten, die ein Ransomware-Angriff sein könnten, zu erkennen und zu warnen. Wird ein Angriff vermutet, erstellt ARP auch neue, unveränderliche Snapshots, anhand derer Sie Ihre Daten wiederherstellen können.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Schützen Sie Ihre Daten mit autonomem Ransomware-Schutz"]



=== Verbesserung des FlexGroup Volume-Ausgleiches

Bei einer BlueXP  Workload-Fabrik wird der FlexGroup Volume Ausgleichs-Assistent mit mehreren Layout-Optionen zur Ausbalancierung der Daten in einem FlexGroup Volume eingeführt. Die Ausbalancierung verteilt Daten gleichmäßig auf die FlexGroup-Mitglieds-Volumes.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["Bringen Sie die Kapazität in einem FlexGroup Volume wieder ins Gleichgewicht"]



=== Implementierung von Best Practices für ein FSX für ONTAP-Filesystem

Die BlueXP  Workload Factory bietet ein Dashboard, über das Sie den gut konzipierten Status Ihrer Filesystem-Konfigurationen überprüfen können. Mithilfe dieser Analyse können Sie Best Practices für Ihre FSX for ONTAP-Dateisysteme implementieren. Die Dateisystemkonfigurationsanalyse umfasst die folgenden Konfigurationen: SSD-Kapazitätsgrenze, geplante lokale Snapshots, geplante FSX für ONTAP-Backups, Daten-Tiering und Remote-Datenreplizierung.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["Informieren Sie sich über die gut konzipierte Analyse für Filesystem-Konfigurationen"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implementieren Sie Best Practices für Ihre Dateisysteme"]




=== Dual-Protokoll-Volume-Sicherheitsoptionen

Sie können entweder NTFS oder UNIX als Sicherheitstil für ein Volume auswählen, um die Methode zu bestimmen, mit der Benutzer und Berechtigungen auf ein Volume zugreifen.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Erstellen eines Volumes"]



=== Verbesserungen bei der Replizierung



==== Unterstützung für umgekehrte Replizierung von FSX für ONTAP nach On-Premises

Die umgekehrte Replizierung ist jetzt von einem FSX für ONTAP-Filesystem zu einem lokalen ONTAP-Cluster in der Workload-Factory-Konsole verfügbar.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/reverse-replication.html["Umgekehrte Replikation"]



==== Datensicherung Volume-Replizierung

Sie können jetzt Datensicherungs-Volumes replizieren.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/cascade-replication.html["Replizierung eines Datensicherheitsvolumes"]



==== Auswahl mehrerer Volumes

Es stehen mehrere Volumeauswahl zur Verfügung, sodass Sie genau die Volumes auswählen können, die Sie replizieren möchten.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Erstellen einer Replikationsbeziehung"]



==== Etiketten für Richtlinien zur langfristigen Aufbewahrung

Wenn Sie die langfristige Aufbewahrung für eine Replikationsbeziehung aktivieren, müssen die Label von Quell- und Ziel-Volumes exakt übereinstimmen. Jetzt kann BlueXP  Workload Factory automatisch fehlende Quell-Volume-Labels für Sie erstellen.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Erstellen einer Replikationsbeziehung"]



=== Der Dateiname FSX for ONTAP ist bei der Volume-Erstellung sichtbar

Wir haben die Sichtbarkeit von FSX für ONTAP-Dateisysteme während der Volume-Erstellung verbessert. Wenn Sie ein Volume erstellen, sehen Sie das FSX für ONTAP-Dateisystem, sodass Sie genau wissen, wo das Volume erstellt wird.



=== AWS-Konto ist für den Storage-Workload sichtbar

Wir haben die Account-Transparenz für den Storage Workload verbessert. Das AWS-Konto wird angezeigt, wenn Sie zu den Registerkarten *Volumes*, *Storage VMs* und *Replication* navigieren.



=== Verbesserungen bei der Verknüpfung

* Sie können einen Link aus einem FSX für ONTAP-Dateisystem in der Registerkarte Inventar schnell verknüpfen.
* BlueXP  Workload Factory unterstützt jetzt die Verwendung alternativer ONTAP-Benutzeranmeldeinformationen für die Link-Zuordnung.




=== Unterstützung der Link-Authentifizierung für AWS Secrets Manager

Sie haben jetzt die Möglichkeit, Secrets von AWS Secrets Manager zum Authentifizieren von Links zu verwenden, sodass Sie keine in der BlueXP  Workload Factory gespeicherten Anmeldeinformationen verwenden müssen.



=== Unterstützung von Tracker-Antworten

Tracker bietet jetzt API-Antworten, sodass Sie die REST API-Ausgabe zu der Aufgabe sehen können.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Überwachen Sie den Betrieb mit Tracker"]



=== Kapazitätsvalidierung beim Wiederherstellen eines Volumes aus einem Backup

Beim Wiederherstellen eines Volumes aus einem Backup ermittelt die BlueXP  Workload Factory, ob Sie über genügend Kapazität für die Wiederherstellung verfügen. Andernfalls kann automatisch SSD-Storage-Tier-Kapazität hinzugefügt werden.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/restore-from-backup.html["Stellen Sie ein Volume aus einem Backup wieder her"]



=== Unterstützung alternativer ONTAP-Benutzeranmeldeinformationen

Workload Factory unterstützt jetzt alternative Sätze von ONTAP-Anmeldeinformationen zur Erstellung von Dateisystemen, um Sicherheitsrisiken zu minimieren. Anstatt nur den Benutzer fsxadmin zu verwenden, können Sie einen anderen Satz von ONTAP-Anmeldeinformationen auswählen oder wählen, kein Passwort für Benutzer von fsxadmin und vsaadmin anzugeben.



=== Terminologie für Berechtigungen wurde aktualisiert

In der Benutzeroberfläche und Dokumentation der Workload Factory wird jetzt „schreibgeschützt“ für Leseberechtigungen und „Lesen/Schreiben“ für automatisierte Berechtigungen verwendet.
