= Unterstützung des BlueXP Workload Factory-Benachrichtigungsdienstes
:allow-uri-read: 




=== Unterstützung des BlueXP Workload Factory-Benachrichtigungsdienstes

Der Benachrichtigungsdienst der BlueXP Workload Factory ermöglicht es der Workload Factory, Benachrichtigungen an den BlueXP-Warndienst oder an ein Amazon SNS-Thema zu senden. An BlueXP-Warnmeldungen gesendete Benachrichtigungen werden im BlueXP-Warnmeldungsbereich angezeigt. Wenn die Workload Factory Benachrichtigungen an ein Amazon SNS-Thema veröffentlicht, erhalten Abonnenten des Themas (z. B. Benutzer oder andere Anwendungen) die Benachrichtigungen an den für das Thema konfigurierten Endpunkten (z. B. per E-Mail oder SMS).

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Konfigurieren Sie die Benachrichtigungen der BlueXP-Workload-Factory"^]



=== Verbesserungen des Speicher-Dashboards

Das Speicher-Dashboard in der Workload Factory-Konsole enthält neue Karten für Einsparmöglichkeiten. Die Karte oben im Dashboard zeigt die Anzahl der Einsparmöglichkeiten für Speicherumgebungen an, die auf Amazon Elastic Block Store (EBS), Amazon FSx für Windows File Server und Amazon Elastic File Systems (EFS) ausgeführt werden. Unten im Dashboard zeigen drei neue Karten Einsparmöglichkeiten nach Amazon-Speicherdienst an – EBS, FSx für Windows File Server und EFS. Auf allen Karten können Sie die Einsparmöglichkeiten detaillierter erkunden.

Anhand der FSx for ONTAP-Schutzabdeckungskarte und der Integritätskarte für Replikationsbeziehungen können Sie prüfen, ob Ihre FSx for ONTAP-Dateisysteme teilweise geschützte Volumes enthalten und Probleme mit Replikationsbeziehungen untersuchen. In beiden Fällen können Sie Maßnahmen zur Behebung der Probleme ergreifen.



=== Verbesserungen der Registerkarte „Lautstärke“

Die Registerkarte „Volumes“ in der Workload Factory-Konsole wurde erweitert, um eine umfassendere Ansicht Ihrer FSx for ONTAP-Dateisysteme zu bieten. Zu den Erweiterungen gehören neue Karten für SSD-Kapazität, Kapazitätspool und NetApp Autonomous Ransomware Protection mit KI (ARP/AI). Diese Karten fassen die Kapazitätsauslastung und den ARP/AI-Schutz für alle Volumes im Dateisystem zusammen.



=== Unterstützung für die zweite Generation von Amazon FSX für NetApp ONTAP-Filesystemen

Workload Factory unterstützt jetzt Amazon FSx für NetApp ONTAP-Dateisysteme der zweiten Generation. Sie können Dateisysteme der zweiten Generation in der Workload Factory-Konsole erstellen, verwalten und überwachen. Alle neuen kommerziellen Regionen werden unterstützt.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Erstellen Sie ein Dateisystem der zweiten Generation in der Workload Factory"]



=== FlexVol-Volume-Unterstützung zum Neuausgleich der Volume-Kapazität

FlexVol-Volumes sind in der Workload Factory-Konsole erkennbar. Sie können die Balance Ihrer FlexVol-Volumes überprüfen und die Kapazität neu verteilen, wenn sich im Laufe der Zeit durch das Hinzufügen neuer Dateien und Dateiwachstum Ungleichgewichte ergeben.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["Neuausgleich der Kapazität eines FlexVol-Volumes"]



=== Terminologie-Update

Der Begriff „Autonomous Ransomware Protection“ (ARP) wurde in der Workload Factory-Konsole in „NetApp Autonomous Ransomware Protection with AI“ (ARP/AI) aktualisiert.



=== ARP/AI standardmäßig für neue Volumes aktiviert

Wenn Sie in der Workload Factory-Konsole ein neues Volume erstellen, ist NetApp Autonomous Ransomware Protection mit KI (ARP/AI) standardmäßig aktiviert, sofern das Dateisystem über eine ARP/AI-Richtlinie verfügt. Das bedeutet, dass das Volume mithilfe KI-gestützter Erkennungs- und Reaktionsfunktionen automatisch vor Ransomware-Angriffen geschützt ist.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Erstellen eines Volumes in der Workload Factory"]



=== Replikationsunterstützung für unveränderliche Dateien

Workload Factory unterstützt die Replikation unveränderlicher Volumes von einem FSx for ONTAP-System auf ein anderes FSx for ONTAP-Dateisystem, um kritische Daten vor versehentlichem Löschen oder böswilligen Angriffen wie Ransomware zu schützen. Das Zielvolume und sein Host-Dateisystem sind unveränderlich bzw. gesperrt, und Daten im Zieldateisystem können bis zum Ende der Aufbewahrungsfrist weder geändert noch entfernt werden.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Erfahren Sie, wie Sie eine Replikationsbeziehung erstellen"]



=== Verwalten der IAM-Ausführungsrolle und -Berechtigungen während der Linkerstellung

Sie können jetzt die IAM-Ausführungsrolle und die zugehörige Berechtigungsrichtlinie verwalten, indem Sie einen Link in der Workload Factory-Konsole erstellen. Ein Link stellt die Verbindung zwischen Ihrem Workload Factory-Konto und einem oder mehreren FSx for ONTAP-Dateisystemen her. Sie haben zwei Möglichkeiten, die IAM-Ausführungsrolle und die Linkberechtigungen zuzuweisen: automatisch oder benutzerdefiniert. Durch die Verwaltung der Ausführungsrolle und der zugehörigen Berechtigungsrichtlinie in der Workload Factory müssen Sie keinen Drittanbietercode mehr verwenden.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Stellen Sie über einen Lambda-Link eine Verbindung zu einem FSX für ONTAP-Dateisystem her"]
