= Unterstützung des BlueXP Workload Factory-Benachrichtigungsdienstes
:allow-uri-read: 




=== Unterstützung des BlueXP Workload Factory-Benachrichtigungsdienstes

Der Benachrichtigungsdienst der BlueXP Workload Factory ermöglicht es der Workload Factory, Benachrichtigungen an den BlueXP-Warndienst oder an ein Amazon SNS-Thema zu senden. An BlueXP-Warnmeldungen gesendete Benachrichtigungen werden im BlueXP-Warnmeldungsbereich angezeigt. Wenn die Workload Factory Benachrichtigungen an ein Amazon SNS-Thema veröffentlicht, erhalten Abonnenten des Themas (z. B. Benutzer oder andere Anwendungen) die Benachrichtigungen an den für das Thema konfigurierten Endpunkten (z. B. per E-Mail oder SMS).

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Konfigurieren Sie die Benachrichtigungen der BlueXP-Workload-Factory"^]

Workload Factory bietet die folgenden Benachrichtigungen für Datenbanken:

* Gut strukturierter Bericht
* Hostbereitstellung




=== Onboarding-Erweiterung für die Registrierung von Instanzen

Workload Factory für Datenbanken hat seinen Onboarding-Prozess für die Registrierung von Instanzen verbessert, die auf Amazon FSx for NetApp ONTAP -Speicher ausgeführt werden.  Sie können jetzt Instanzen in großen Mengen zur Registrierung auswählen.  Sobald eine Instanz registriert ist, können Sie Datenbankressourcen in der Workload Factory-Konsole erstellen und verwalten.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["Instanzverwaltung"]



=== Analyse und Fehlerbehebung für die Microsoft Multipath I/O-Timeout-Einstellung

Der Well-Architected-Status für Ihre Datenbankinstanzen umfasst jetzt die Analyse und den Fix für die Timeout-Einstellung von Microsoft Multipath I/O (MPIO).  Durch Einstellen des MPIO-Timeouts auf 60 Sekunden wird die FSx für ONTAP Speicherkonnektivität und Stabilität während Failovers sichergestellt.  Wenn die MPIO-Einstellung nicht entsprechend festgelegt ist, bietet Workload Factory eine Lösung, um den MPIO-Timeoutwert auf 60 Sekunden festzulegen.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementieren Sie gut strukturierte Datenbankkonfigurationen in der Workload Factory"]



=== Verbesserungen der Grafiken im Instanzinventar

Auf dem Bildschirm „Instanzinventar“ werden jetzt in verschiedenen Diagrammen zur Ressourcenauslastung, beispielsweise zu Durchsatz und IOPS, Daten der letzten 7 Tage angezeigt, sodass Sie die Leistung von SQL-Knoten von der Workload Factory-Konsole aus effizienter überwachen können.  Die von den SQL-Knoten gesammelten Leistungsmetriken werden in Amazon CloudWatch gespeichert und können für Logs Insights oder zur Integration mit anderen Analysediensten in Ihrer Umgebung verwendet werden.

Auf den Registerkarten „Instanzen“ und „Datenbanken“ im Inventar haben wir die Beschreibung und Visualisierung zum Schutz verbessert.



=== Unterstützung für Windows-Authentifizierung in der Workload Factory

Jetzt unterstützt Workload Factory die SQL Server-Authentifizierung mithilfe von Windows-authentifizierten Benutzern, um Instanzen zu registrieren und von Verwaltungsfunktionen zu profitieren.

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html["Registrieren Sie Instanzen in der Workload Factory für Datenbanken"]
