= PostgreSQL- und Oracle-Erkennung
:allow-uri-read: 




=== PostgreSQL- und Oracle-Erkennung

Sie können jetzt die Instanzen, die PostgreSQL-Serverdatenbanken und Oracle-Datenbankbereitstellungen in Ihrem AWS-Konto ausführen, in der Workload Factory-Konsole ermitteln. Erkannte Instanzen werden im Datenbankinventar angezeigt.



=== Aktualisierte Terminologie „Optimierung“

Workload Factory wurde früher als „Optimierung“ bezeichnet und verwendet jetzt „Well-Architected Issues“ und „Well-Architected Status“, um die Analyse von Datenbankkonfigurationen zu beschreiben, und „Fix“, um Abhilfemaßnahmen für Möglichkeiten zur Verbesserung von Datenbankkonfigurationen zu beschreiben, um Best-Practice-Empfehlungen zu erfüllen.

link:https://docs.netapp.com/us-en/workload-databases/optimize-overview.html["Konfigurationsanalyse für Datenbankumgebungen in der Workload Factory"]



=== Verbessertes Onboarding für Host-Instanzen

Anstelle der Begriffe „unerkannt“, „unverwaltet“ oder „verwaltet“ für die Verwaltung von Hostinstanzen verwendet Workload Factory jetzt „Registrieren“ für das Onboarding von Hostinstanzen. Der neue Registrierungsprozess umfasst die Authentifizierung und Vorbereitung von Hostinstanzen, sodass Sie Ressourcen in Ihren Datenbankkonfigurationen in der Workload Factory-Konsole erstellen, überwachen, analysieren und reparieren können. Der Vorbereitungsschritt im Registrierungsprozess zeigt an, ob Ihre Hostinstanzen für die Verwaltung bereit sind.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["Instanzmanagement"]
