= Automatisches Kapazitätsmanagement für Scale-out-Systeme
:allow-uri-read: 




=== Automatisches Kapazitätsmanagement für Scale-out-Systeme

Workload Factory sucht nun nach verfügbaren Inodes in Volumes und erhöht ihre Anzahl entsprechend den konfigurierten Schwellenwerten für das automatische Kapazitätsmanagement. Diese Funktion unterstützt automatisches Kapazitätsmanagement für Scale-out-Systeme. Sie können das Inodes-Management im Rahmen des automatischen Kapazitätsmanagements aktivieren.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["Aktivieren Sie das automatische Kapazitätsmanagement"]



=== FlexGroup-AusgleichAPI

An der BlueXP  Workload-Fabrik wird die FlexGroup-Ausgleichs-API veröffentlicht, über die Sie einen Plan zum Lastausgleich der Daten in einer FlexGroup ausführen können. Durch die Ausbalancierung werden Daten gleichmäßig auf die Mitglieds-Volumes verteilt.

link:https://console.workloads.netapp.com/api-doc["BlueXP  Workload-API-Dokumentation"]



=== Datenform zur Replizierung umfasst Anwendungsfälle

Das Formular Daten replizieren enthält jetzt Anwendungsfälle, um das Ausfüllen des Formulars zu erleichtern. Wählen Sie einen der folgenden Anwendungsfälle für die Datenreplizierung aus: Migration, Disaster Recovery für häufig benötigte Daten, Cold-Disaster-Recovery, Archivierung oder andere. Nachdem Sie einen Anwendungsfall ausgewählt haben, empfiehlt Workload Factory Werte im Einklang mit Best Practices. Sie können die vorausgewählten Werte akzeptieren oder die Werte im Formular anpassen.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Datenreplizierung"]



=== Änderungen der Terminologie bei der Data Tiering-Richtlinie

Wenn Sie sich nun für eine Tiering-Richtlinie während der Volume-Erstellung, Datenreplizierung oder Aktualisierung vorhandener Tiering-Richtlinien entscheiden, finden Sie neue Begriffe zur Beschreibung der Tiering-Richtlinien.

* _Ausgeglichen (Auto)_
* _Kostenoptimiert (Alle)_
* _Performance Optimized (nur Snapshots)_

