= Unterstützung des BlueXP Workload Factory-Benachrichtigungsdienstes
:allow-uri-read: 




=== Unterstützung des BlueXP Workload Factory-Benachrichtigungsdienstes

Der Benachrichtigungsdienst der BlueXP Workload Factory ermöglicht es der Workload Factory, Benachrichtigungen an den BlueXP-Warndienst oder an ein Amazon SNS-Thema zu senden. An BlueXP-Warnmeldungen gesendete Benachrichtigungen werden im BlueXP-Warnmeldungsbereich angezeigt. Wenn die Workload Factory Benachrichtigungen an ein Amazon SNS-Thema veröffentlicht, erhalten Abonnenten des Themas (z. B. Benutzer oder andere Anwendungen) die Benachrichtigungen an den für das Thema konfigurierten Endpunkten (z. B. per E-Mail oder SMS).

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Konfigurieren Sie die Benachrichtigungen der BlueXP-Workload-Factory"^]

Workload Factory bietet die folgenden Benachrichtigungen für Datenbanken:

* Gut strukturierter Bericht
* Hostbereitstellung
* Darstellt




=== Onboarding-Erweiterung für die Registrierung von Instanzen

Workload Factory für Datenbanken hat den Onboarding-Prozess für die Registrierung von Instanzen auf Amazon FSx für NetApp ONTAP-Speicher verbessert. Sie können jetzt Instanzen gleichzeitig zur Registrierung auswählen. Sobald eine Instanz registriert ist, können Sie Datenbank-Host-Ressourcen in der Workload Factory-Konsole erstellen und verwalten.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["Instanzmanagement"]



=== Analyse und Fehlerbehebung für die Microsoft Multipath I/O-Timeout-Einstellung

Der Well-Architected-Status für Ihre Datenbankhostinstanzen umfasst nun die Analyse und den Fix für die Microsoft Multipath I/O (MPIO)-Timeout-Einstellung. Die Einstellung des MPIO-Timeouts auf 60 Sekunden gewährleistet die FSx für ONTAP-Speicherkonnektivität und Stabilität bei Failovers. Sollte die MPIO-Einstellung nicht entsprechend eingestellt sein, stellt Workload Factory einen Fix bereit, um den MPIO-Timeout-Wert auf 60 Sekunden festzulegen.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementieren Sie gut strukturierte Datenbankkonfigurationen in der Workload Factory"]



=== Verbesserungen der Grafiken im Host-Inventar

Auf dem Host-Inventarbildschirm werden jetzt verschiedene Diagramme zur Ressourcenauslastung, wie Durchsatz und IOPS, mit Daten der letzten 7 Tage angezeigt. So können Sie die Leistung von SQL-Knoten über die Workload Factory-Konsole effizienter überwachen. Die von den SQL-Knoten erfassten Leistungsmetriken werden in Amazon CloudWatch gespeichert und können für Logs Insights oder die Integration mit anderen Analysediensten in Ihrer Umgebung verwendet werden.

Auf den Registerkarten „Instanzen“ und „Datenbanken“ im Hostinventar haben wir die Beschreibung und Visualisierung für den Hostschutz verbessert.



=== Unterstützung für Windows-Authentifizierung in der Workload Factory

Jetzt unterstützt Workload Factory die SQL Server-Authentifizierung mithilfe von Windows-authentifizierten Benutzern, um Hostinstanzen zu registrieren und von Hostverwaltungsfunktionen zu profitieren.

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html["Registrieren Sie Hostinstanzen in der Workload Factory für Datenbanken"]
