= PostgreSQL-Hochverfügbarkeitskonfiguration
:allow-uri-read: 




=== PostgreSQL-Hochverfügbarkeitskonfiguration

Sie können jetzt eine HA-Konfiguration für PostgreSQL Server implementieren.

link:https://review.docs.netapp.com/us-en/workload-databases_explore-savings-updates/create-postgresql-server.html["Erstellen Sie einen PostgreSQL-Server"]



=== Terraform-Unterstützung für die PostgreSQL-Servererstellung

Sie können jetzt Terraform aus der Codebox verwenden, um PostgreSQL zu implementieren.

* link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["Erstellen Sie einen PostgreSQL-Datenbankserver"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Verwenden Sie Terraform aus der Codebox"]




=== Stabilitätsbewertung für lokalen Snapshot-Zeitplan

Für Datenbank-Workloads steht eine neue Bewertung der Ausfallsicherheit zur Verfügung. Wir bewerten, ob Volumes für Ihre Microsoft SQL Server Instanzen gültige geplante Snapshot-Richtlinien aufweisen. Snapshots sind zeitpunktgenaue Kopien Ihrer Daten und sorgen dafür, dass Ihre Datenbankumgebungen auch bei Datenverlusten ausfallsicher bleiben.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimieren von Konfigurationen"]



=== MAXDOP-Korrektur für Datenbank-Workloads

Die BlueXP -Workload-Fabrik für Datenbanken unterstützt jetzt die Wiederherstellung der maximalen Parallelität (Maximum Degree of Parallelism, MAXDOP)-Serverkonfiguration. Wenn die MAXDOP-Konfiguration nicht optimal ist, können Sie die Konfiguration für die BlueXP -Workload Factory optimieren lassen.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimieren von Konfigurationen"]



=== Bericht zur Einsparungsanalyse per E-Mail

Wenn Sie die Einsparungen für Ihre Amazon Elastic Block Store und FSX für Windows File Server Storage-Umgebungen im Vergleich zu FSX für ONTAP erkunden, können Sie sich nun den Empfehlungsbericht per E-Mail an sich selbst, Teammitglieder und Kunden senden.
