= Cache-Volume-Verwaltung
:allow-uri-read: 




=== Cache-Volume-Verwaltung

Die folgenden Vorgänge zur Verwaltung des Cache-Volumes können Sie in der Workload Factory-Konsole durchführen:

* Cache-Namen bearbeiten
* Erhöhen Sie die Kapazität eines Cache-Volumes
* Bearbeiten Sie den Mount-Pfad oder die Exportrichtlinie für ein Cache-Volume.
* Ändern Sie die Caching-Methode oder den Modus für ein Cache-Volume.
* Cache-Volume vorbefüllen
* Löschen eines Cache-Volumes


link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["Cache-Volumes verwalten"]



=== Automatisches Inode-Management verfügbar

Die automatische Inode-Verwaltung kann aktiviert werden, ohne dass die automatische Kapazitätsverwaltung aktiviert werden muss.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["Automatische Inode-Verwaltung aktivieren"]



=== Schwellenwertwarnung für Kapazitäts- und Inode-Nutzung

Schwellenwertwarnungen sind sowohl für die Kapazität als auch für die Inode-Auslastung verfügbar. Diese Schwellenwerte können Sie beim Aktivieren der automatischen Kapazitäts- oder Inode-Verwaltung festlegen. Um diese Einstellung zu verwenden, müssen Sie Benachrichtigungen mithilfe der folgenden Funktion konfigurieren:link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["NetApp Workload Factory Benachrichtigungsdienst"^] Die



=== Volumenverkleinerung möglich

Sie können die Größe von NFS- und SMB/CIFS-Volumes in NetApp Workload Factory verringern. Diese Funktion ermöglicht eine bessere Verwaltung der Speicherressourcen, indem sie es Ihnen erlaubt, die Größe von Volumes zu reduzieren, die in ihrer aktuellen Kapazität nicht mehr benötigt werden.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/adjust-volume-capacity.html["Verringern Sie die Kapazität eines Volumens"]



=== Erweiterter FSx für ONTAP Ressourcenstatus

Workload Factory hat den Ressourcenstatus „falsch konfiguriert“ um eine Erläuterung des eigentlichen Problems für die Ressource erweitert.



=== Gut strukturierte Analyse-Updates

Workload Factory analysiert Ihre FSx for ONTAP Dateisysteme für die folgenden Konfigurationen:

* Die Speicherauslastung nähert sich der maximalen Kapazität: Es wird geprüft, ob Speichermedien 80 % oder mehr ihrer Dateikapazität nutzen. Dies hilft Ihnen, Volumina zu identifizieren, die möglicherweise zusätzliche Kapazität benötigen.
* Unberechtigter Zugriff auf Volumes: Prüft, ob ein iSCSI-Volume über einen NFS- oder SMB/CIFS-Mountpfad erreichbar ist, und ermöglicht es Ihnen, unberechtigten Zugriff auf das Volume zu entfernen, um Sicherheitsrisiken zu vermeiden.




=== Berechtigungsänderungen für Workload Factory für Speicher

Workload Factory bietet mehr Klarheit darüber, welche Berechtigungen für bestimmte Aktionen erforderlich sind, und ermöglicht die detaillierte Auswahl nur der benötigten Berechtigungen. Wenn Sie Anmeldeinformationen hinzufügen, stehen Ihnen drei Berechtigungsoptionen zur Auswahl, anstatt des bisherigen Berechtigungsmodells mit den Optionen „Nur lesen“ und „Lesen/Schreiben“. Das neue Berechtigungsmodell unterteilt die Berechtigungsrichtlinien wie folgt:

* _Ansicht, Planung und Analyse_: Sehen Sie sich FSx for ONTAP -Dateisysteme an, erfahren Sie mehr über den Systemzustand, erhalten Sie eine fundierte Analyse Ihrer Systeme und entdecken Sie Einsparmöglichkeiten.
* _Betrieb und Fehlerbehebung_: Führen Sie operative Aufgaben durch, wie z. B. die Anpassung der Dateisystemkapazität und die Behebung von Problemen in Ihren Dateisystemkonfigurationen.
* _Dateisystemerstellung und -löschung_: Erstellen und Löschen von FSx-Dateisystemen und Speicher-VMs für ONTAP .


Beim Hinzufügen von Anmeldeinformationen können Sie eine oder mehrere dieser Berechtigungsrichtlinien auswählen, je nachdem, welchen Zugriff Sie Workload Factory gewähren möchten.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Referenz zu den Berechtigungen der Workload Factory"]



=== FSx für ONTAP Cyber ​​Vault-Unterstützung

Sie können einen Cyber-Tresor erstellen, indem Sie FSx für ONTAP als Quelle oder Ziel in der Cyber-Tresor-Architektur verwenden. Cyber-Tresore bieten eine sichere und isolierte Umgebung zur Speicherung kritischer Daten und schützen diese vor Ransomware und anderen Cyberbedrohungen.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-cyber-vault.html["Richten Sie einen Cyber-Tresor mit FSx für ONTAP ein."]
