= Volumes Explorer
:allow-uri-read: 




[[volumes-explorer]]
=== Volumes Explorer

Volumes Explorer bietet eine einfache, durchsuchbare Ansicht aller Volumes in NetApp Workload Factory. Es wird schnell ersichtlich, welche Volumes Block- oder Datei-Workloads bedienen. Die logische Größe, die physisch genutzte Kapazität und die Nutzung von Speichereffizienzfunktionen (Komprimierung, Deduplizierung und Verdichtung) jedes Volumes werden angezeigt. Eine Filterung und Sortierung nach Name, Status (verfügbar/ausgefallen), Latenz, Größe, genutzter Kapazität und Schutzfunktionen ist möglich.



[[enhanced-email-notifications-for-replication-delays]]
=== Verbesserte E-Mail-Benachrichtigungen bei Replikationsverzögerungen

E-Mail-Benachrichtigungen über Replikationsverzögerungen enthalten jetzt detailliertere Informationen zur betroffenen Beziehung. Die Benachrichtigung ermöglicht eine schnelle Identifizierung der betroffenen Beziehung und eine weitere Untersuchung in der Workload Factory Konsole.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-replication-delays.html["Benachrichtigungen für Replikationsverzögerungen aktivieren"]



[[block-device-creation-enhancement]]
=== Verbesserung der Blockgeräteerstellung

Workload Factory unterstützt die Erstellung von Blockgeräten aus einem Volume Snapshot.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-block-device.html["Ein Blockgerät aus einem Volume-Snapshot in Workload Factory erstellen"]
