= Einführung der Unterstützung für Migration Advisor für Google Cloud VMware Engine
:allow-uri-read: 




=== Einführung der Unterstützung für Migration Advisor für Google Cloud VMware Engine

NetApp Workload Factory unterstützt jetzt Google Cloud VMware Engine. Sie können Ihre lokalen VMware-Workloads zu Google Cloud VMware Engine migrieren, indem Sie Google Cloud NetApp Volumes als externe NFS-Datenspeicher verwenden. Dadurch werden die Kosten optimiert und Sie erhalten mehr Kontrolle über Ihre VMware-Umgebung, ohne Ihre Anwendungen refaktorisieren oder auf eine neue Plattform umstellen zu müssen.

Der Google Cloud VMware Engine Migrationsberater bietet:

* Automatisierte Dimensionierung und Auslegung von Google Cloud VMware Engine-Clustern mit Unterstützung für VE1- und VE2-Knotentypen
* VM-Layoutoptimierung zwischen internen vSAN-Datenspeichern und Google Cloud NetApp Volumes externen NFS-Datenspeichern.
* Detaillierter Kostenvergleich und TCO-Analyse zwischen reinen vSAN- und Google Cloud NetApp Volumes-basierten Konfigurationen.
* Unterstützung für die Servicelevel Standard, Premium und Extreme des Google Cloud NetApp Volumes.
* Infrastructure-as-Code-Bereitstellung mit Terraform für die automatisierte Bereitstellung.

