= Gut konzipierte Analyse für Oracle
:allow-uri-read: 




=== Gut konzipierte Analyse für Oracle

Die gut durchdachte Analyse umfasst die folgenden neuen Konfigurationen für Oracle:

* *Oracle Critical Patch Updates*: Bewertet fehlende Sicherheitspatches für unterstützte selbstverwaltete Oracle-Datenbankinstallationen.
* *Regionsübergreifende Replikation*: Prüft, ob die regionsübergreifende Replikation (CRR) für Ihre FSx for ONTAP Dateisysteme, die Oracle Datenbanken bedienen, aktiviert ist.
* *Applikationskonsistente Snapshots*: prüft, ob die Oracle Datenbank durch applikationskonsistente Snapshots mit NetApp SnapCenter geschützt ist.


link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementieren Sie gut strukturierte Datenbankkonfigurationen in Workload Factory"]



=== Einmalige Bewertung für Oracle

Workload Factory bietet jetzt eine einmalige Analyse Ihrer Oracle Datenbank-Bereitstellungen – wann immer Sie diese benötigen: bei Neuinstallationen, nach Migrationen, bei der Fehlerbehebung und mehr. Sie erhalten Empfehlungen zur Optimierung Ihrer Bereitstellungskonfigurationen und zur Einhaltung von Best Practices. Dies ist Ihre Gelegenheit, die well-architected Funktion zu nutzen, ohne sich vollständig auf den Einrichtungsprozess festlegen zu müssen. Sie können Ihre Datenbanken analysieren, ohne Anmeldeinformationen in Workload Factory zu speichern, Datenbankressourcen zu registrieren oder externe Verbindungen einzurichten.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Führen Sie eine einmalige Bewertung Ihrer Oracle-Datenbankbereitstellungen durch"]



=== Verbesserte Kosteneinsparungen für mehrere Oracle-Datenbanken

Wir haben die Kostenanalyse für Oracle optimiert, um eine konsolidierte Speicherlösung für mehrere lokale Oracle-Datenbanken auf einem FSx for ONTAP-Dateisystem bereitzustellen. Diese Konsolidierung optimiert die Speicherkosten, indem die Anzahl der für mehrere Datenbanken benötigten Dateisysteme reduziert wird, was zu höheren Kosteneinsparungen führt.

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["Entdecken Sie Einsparungen für erkannte Datenbanken auf Oracle On-Premises."]
